<?php
$root = dirname(__DIR__);
function m10_source($path) { $value = file_get_contents(dirname(__DIR__) . DIRECTORY_SEPARATOR . $path); if ($value === FALSE) throw new RuntimeException('Tidak dapat membaca ' . $path); return $value; }
function m10_check($condition, $message) { if (!$condition) throw new RuntimeException($message); }

$migration = m10_source('migrations/020_create_spmi_reports.sql');
$version_report_migration = m10_source('migrations/037_add_spmi_version_report_scope.sql');
$academic_year_migration = m10_source('migrations/043_add_spmi_report_academic_year_snapshot.sql');
$version_auditee_migration = m10_source('migrations/044_add_spmi_version_auditee_report_scope.sql');
$schema = m10_source('database_schema.sql');
$model = m10_source('application/models/Spmi_reports_model.php');
$service = m10_source('application/services/Spmi_reports_service.php');
$controller = m10_source('application/controllers/lpmpi/Spmi_reports.php');
$routes = m10_source('application/config/routes.php');
$sidebar = m10_source('application/views/layouts/sidebar.php');
$index = m10_source('application/views/lpmpi/spmi_reports/index.php');
$detail = m10_source('application/views/lpmpi/spmi_reports/detail.php');
$print = m10_source('application/views/lpmpi/spmi_reports/print.php');
$word = m10_source('application/views/lpmpi/spmi_reports/word.php');
$final_result = m10_source('application/views/spmi_auditee_workspace/final_result.php');
$auditor_evidence_migration = m10_source('migrations/029_add_spmi_auditor_assessment_evidence.sql');

foreach (['spmi_reports', 'spmi_report_items', 'UNIQUE KEY `uq_spmi_reports_assessment`', 'UNIQUE KEY `uq_spmi_reports_report_number`', 'generated_by', 'generated_at', 'descriptor_snapshot', '`score` TINYINT UNSIGNED NOT NULL', 'ON DELETE RESTRICT', 'ON UPDATE RESTRICT'] as $literal) m10_check(strpos($migration, $literal) !== FALSE, 'M10 migration contract missing: ' . $literal);
m10_check(!preg_match('/(^|;|\R)\s*(INSERT|UPDATE|DELETE)\s+/i', $migration), 'M10 migration must be seed-free.');
foreach (['current parity migration 001-030', 'spmi_reports', 'spmi_report_items', 'uq_spmi_reports_assessment', 'uq_spmi_reports_report_number', 'uq_spmi_report_items_order'] as $literal) m10_check(strpos($schema, $literal) !== FALSE, 'M10 schema parity missing: ' . $literal);
foreach (['report_scope', 'source_cycle_id', 'source_version_id', 'auditor_id_snapshot', 'auditee_id_snapshot', 'uq_spmi_reports_version_tuple', 'source_standard_id', 'source_standard_code_snapshot', 'source_standard_title_snapshot', 'source_standard_display_order', 'standard_item_display_order', 'INFORMATION_SCHEMA.COLUMNS'] as $literal) m10_check(strpos($version_report_migration . $schema, $literal) !== FALSE, 'Version report migration/schema contract missing: ' . $literal);
m10_check(!preg_match('/(^|;|\R)\s*(INSERT|UPDATE|DELETE)\s+/i', $version_report_migration), 'Version report migration must not rewrite historical reports.');
foreach (['INFORMATION_SCHEMA.COLUMNS', 'INFORMATION_SCHEMA.STATISTICS', 'academic_year_snapshot', 'VARCHAR(20) NULL', 'idx_spmi_reports_academic_year_generated'] as $literal) m10_check(strpos($academic_year_migration . $schema, $literal) !== FALSE, 'Academic-year snapshot migration/schema contract missing: ' . $literal);
m10_check(!preg_match('/(^|;|\R)\s*(INSERT|UPDATE|DELETE)\s+/i', $academic_year_migration), 'Academic-year snapshot migration must not backfill history.');
foreach (['version_auditee', 'version_auditee_scope_guard', 'GENERATED ALWAYS AS', "CASE WHEN `report_scope` = 'version_auditee' THEN 1 ELSE NULL END", 'auditor_id_snapshot', 'auditor_name_snapshot', 'auditor_email_snapshot', 'uq_spmi_reports_version_auditee_tuple', 'INFORMATION_SCHEMA.COLUMNS', 'INFORMATION_SCHEMA.STATISTICS'] as $literal) m10_check(strpos($version_auditee_migration . $schema, $literal) !== FALSE, 'Version-auditee migration/schema contract missing: ' . $literal);
m10_check(strpos($version_auditee_migration, '(`source_cycle_id`, `source_version_id`, `auditee_id_snapshot`, `report_scope`)') === FALSE && strpos($schema, '(`source_cycle_id`, `source_version_id`, `auditee_id_snapshot`, `report_scope`)') === FALSE, 'Version-auditee uniqueness must not constrain legacy standard/version report scope rows.');
m10_check(!preg_match('/(^|;|\R)\s*(INSERT|UPDATE|DELETE)\s+/i', $version_auditee_migration), 'Version-auditee migration must not rewrite historical reports.');
foreach (['assessment_for_update', 'cycle_for_update', 'submission_for_update', 'report_for_assessment_for_update', 'insert_item', 'report_by_id', 'reports', 'FOR UPDATE'] as $literal) m10_check(strpos($model, $literal) !== FALSE, 'M10 model contract missing: ' . $literal);
foreach (['trans_begin', 'finalized', 'submitted', 'configured', 'closed', 'score', 'descriptor', 'realization_snapshot', 'affected_rows', 'report_number'] as $literal) m10_check(strpos($service, $literal) !== FALSE, 'M10 service contract missing: ' . $literal);
foreach (['finalized_versions', 'MAX(CASE WHEN s.id IS NOT NULL THEN aa.id END)', 'version_auditee_report_for_update', 'assignments_for_version_auditee_report_for_update', 'finalized_assessment_for_assignment_for_update', 'version_auditee', 'source_version_id', 'source_standard_display_order', 'COUNT(DISTINCT CASE WHEN s.id IS NOT NULL THEN a.id END)'] as $literal) m10_check(strpos($model . $service, $literal) !== FALSE, 'Version report model/service contract missing: ' . $literal);
foreach (['index_options($filters = NULL)', 'options_query', 'index_count', 'index_reports', 'index_summary', 'index_standard_analysis', 'apply_index_filters', 'academic_year_snapshot', 'spmi_reports r', 'spmi_report_items ri', 'generated_at', 'COUNT(DISTINCT r.id)'] as $literal) m10_check(strpos($model, $literal) !== FALSE, 'Snapshot index model contract missing: ' . $literal);
foreach (['index_data', 'normalize_index_filters', 'academic_year', 'cycle_id', 'version_id', 'auditee_id', "'q'", "'page'", 'per_page', '20', 'in_array'] as $literal) m10_check(strpos($service, $literal) !== FALSE, 'Snapshot index service/filter contract missing: ' . $literal);
m10_check(strpos($controller, 'index_data($this->input->get(NULL, TRUE))') !== FALSE && strpos($controller, "'index_data' => $" . 'index_data') !== FALSE, 'Controller must expose one snapshot index view model.');
$index_model = substr($model, strpos($model, 'public function index_options()'), strpos($model, 'public function finalized_assessments()') - strpos($model, 'public function index_options()'));
foreach (['spmi_audit_cycles', 'spmi_audit_assignments', 'users', 'spmi_versions', 'spmi_auditor_assessments', 'spmi_auditee_submissions', 'spmi_auditee_evidence'] as $forbidden) m10_check(strpos($index_model, $forbidden) === FALSE, 'Snapshot index must not join live data: ' . $forbidden);
m10_check(strpos($index_model, "if (\$filters['academic_year'] !== '') \$query->where('r.academic_year_snapshot', \$filters['academic_year']);") !== FALSE, 'Selected academic year must only read the immutable snapshot, excluding NULL history.');
m10_check(strpos($service, "'q' => substr(\$value('q'), 0, 120)") !== FALSE && strpos($index_model, "->like('r.report_number', \$filters['q'])") !== FALSE, 'Snapshot search must be bounded and query-builder bound.');
m10_check(strpos($service, '$this->model->index_options($filters)') !== FALSE && substr_count($service, '$this->normalize_index_filters($input,') === 2, 'Snapshot filter IDs must be revalidated against contextual snapshot options.');
m10_check(preg_match('/index_data\(\$input\).*index_reports\(\$filters, 20, \(\$filters\[\'page\'\] - 1\) \* 20\)/s', $service) === 1 && substr_count($service, 'index_reports(') === 1, 'Snapshot history must fetch one deterministic 20-row page without N+1 reads.');
m10_check(strpos($model, "if (\$positive_id_column !== NULL) \$query->where(\$positive_id_column . ' >', 0);") !== FALSE && strpos($model, "'versions' => \$options_query('source_version_id, source_version_code_snapshot, source_version_title_snapshot', 'source_version_id, source_version_code_snapshot, source_version_title_snapshot', ['source_version_code_snapshot', 'DESC'], 'r.source_version_id')") !== FALSE && strpos($model, "'auditees' => \$options_query('auditee_id_snapshot, auditee_name_snapshot', 'auditee_id_snapshot, auditee_name_snapshot', ['auditee_name_snapshot', 'ASC'], 'r.auditee_id_snapshot')") !== FALSE, 'Phase 1 report Version/Auditee options must exclude NULL/nonpositive snapshot IDs before the view can cast them to value 0.');
$unfiltered_history_model = substr($model, strpos($model, 'public function index_count('), strpos($model, 'protected function apply_index_filters(') - strpos($model, 'public function index_count('));
m10_check(strpos($unfiltered_history_model, "source_version_id . ' >'") === FALSE && strpos($unfiltered_history_model, "auditee_id_snapshot . ' >'") === FALSE && strpos($unfiltered_history_model, 'positive_id_column') === FALSE, 'Phase 1 all-years/unfiltered history queries must still include historical reports with NULL Version/Auditee IDs.');
foreach (['finalized_versions', 'anchor_assessment_id', 'standards', 'source_standard_code_snapshot', 'source_standard_title_snapshot', 'standard_item_display_order', 'contributors', 'auditor_email_snapshot'] as $literal) m10_check(strpos($controller . $index . $detail . $print . $word, $literal) !== FALSE, 'Version report controller/view grouping contract missing: ' . $literal);
foreach (['extends Admin_Lpmpi_Controller', "method(TRUE) !== 'POST'", 'generate', 'export', 'export_word', 'print', 'Spmi_reports_service', 'show_error'] as $literal) m10_check(strpos($controller, $literal) !== FALSE, 'M10 controller contract missing: ' . $literal);
foreach (['lpmpi/spmi-reports', 'assessment/create/(:num)', 'detail/(:num)', 'export/(:num)', 'export-word/(:num)', 'print/(:num)'] as $literal) m10_check(strpos($routes, $literal) !== FALSE, 'M10 route missing: ' . $literal);
m10_check(substr_count($sidebar, "'key' => 'spmi_reports', 'label' => 'Laporan SPMI', 'icon' => 'fa-file-alt', 'url' => 'lpmpi/spmi-reports', 'group' => 'Insights'") === 2, 'M10 sidebar entry must exist only for management roles.');
m10_check(strpos($index, '<h1 class="tw-text-3xl tw-font-bold tw-tracking-tight tw-text-slate-950">Laporan SPMI</h1>') !== FALSE && strpos($index, 'Kelola, tinjau, dan ekspor hasil audit mutu yang telah difinalisasi.') !== FALSE, 'Phase 1 index must keep the snapshot dashboard title and subtitle.');
m10_check(
    strpos($index, '<header class="reports-header') < strpos($index, 'id="snapshot-summary-title"')
    && strpos($index, 'id="snapshot-summary-title"') < strpos($index, 'id="report-filter-title"')
    && strpos($index, 'id="report-filter-title"') < strpos($index, 'id="report-list-title"')
    && strpos($index, 'id="standard-analysis-title"') === FALSE,
    'SPMI report index sections must remain ordered: header -> summary -> filter -> list, without standard analysis.'
);
m10_check(strpos($index, "form_open('lpmpi/spmi-reports', ['method' => 'get'") !== FALSE && strpos($index, "name=\"academic_year\"") !== FALSE && strpos($index, "name=\"cycle_id\"") !== FALSE && strpos($index, "name=\"academic_year\"") < strpos($index, "name=\"cycle_id\"") && strpos($index, "name=\"q\"") !== FALSE && strpos($index, "name=\"version_id\"") !== FALSE && strpos($index, "name=\"auditee_id\"") !== FALSE && strpos($index, "query['page']") !== FALSE, 'Phase 1 index GET filters must include academic_year before cycle_id plus q, version_id, auditee_id, and page.');
m10_check(strpos($index, 'Belum ada snapshot yang cocok dengan filter ini. Coba ubah filter atau tampilkan semua riwayat laporan.') !== FALSE, 'Phase 1 index empty message must describe unmatched snapshot filters exactly.');
m10_check(strpos($index, 'html_escape($year->academic_year_snapshot)') !== FALSE && strpos($index, 'html_escape($cycle->cycle_code_snapshot') !== FALSE && strpos($index, 'html_escape($report->report_number)') !== FALSE, 'Phase 1 index must escape snapshot filters and list rows.');
m10_check(strpos($index, 'tw-hidden tw-overflow-hidden') !== FALSE && strpos($index, 'md:tw-hidden') !== FALSE && strpos($index, '<table class="tw-w-full tw-text-left tw-text-sm">') !== FALSE && strpos($index, '<article class="tw-rounded-2xl') !== FALSE, 'Phase 1 index must expose semantic desktop table and mobile cards.');
m10_check(strpos($index, "site_url('lpmpi/spmi-reports/detail/' . (int) \$report->id)") !== FALSE && strpos($index, "site_url('lpmpi/spmi-reports/print/' . (int) \$report->id)") !== FALSE && strpos($index, "site_url('lpmpi/spmi-reports/export/' . (int) \$report->id)") !== FALSE && strpos($index, '>Detail</a>') !== FALSE && strpos($index, '>Print</a>') !== FALSE && strpos($index, '>XLSX</a>') !== FALSE, 'Phase 1 index must keep direct Detail, Print, and XLSX actions per report.');
m10_check(strpos($index, 'aria-live="polite"') !== FALSE && strpos($index, 'aria-label="Navigasi halaman laporan"') !== FALSE && strpos($index, 'aria-current="page"') !== FALSE && strpos($index, 'rel="prev"') !== FALSE && strpos($index, 'rel="next"') !== FALSE, 'Phase 1 index must keep accessible live result counts and pagination.');
m10_check(strpos($index, "form_open('lpmpi/spmi-reports/assessment/create/' . (int) \$assessment->anchor_assessment_id") !== FALSE && strpos($index, 'type="submit"') !== FALSE && strpos($index, 'Generate laporan') !== FALSE, 'Phase 1 index must preserve POST report generation forms and CSRF helper usage.');
m10_check(strpos($index, 'chart.js') === FALSE && strpos($index, 'new Chart') === FALSE && strpos($index, 'report-row') === FALSE && strpos($index, 'data-report') === FALSE && strpos($index, 'Tahun akademik -> Siklus -> Kelompok penugasan') === FALSE, 'Phase 1 index must not restore old client filtering, export selector, or index Chart.js.');
m10_check(strpos($detail, 'html_escape') !== FALSE && strpos($detail, 'nl2br(html_escape(') !== FALSE && strpos($print, 'html_escape') !== FALSE && strpos($print, 'nl2br(html_escape(') !== FALSE, 'M10 detail/print views must escape text and multiline snapshots.');
m10_check(strpos($detail, 'spmi_report_items') === FALSE && strpos($print, 'spmi_report_items') === FALSE, 'M10 detail/print must not expose source table names.');
foreach (['TYPE_STRING', 'setCellValueExplicit', 'formula_prefixes', 'while (ob_get_level() > 0)', 'Save as PDF', 'window.print'] as $literal) m10_check(strpos($controller, $literal) !== FALSE || strpos($print, $literal) !== FALSE, 'M10 export/print contract missing: ' . $literal);
foreach (["\$data['items']", 'indicator_code_snapshot', 'Data Radar', 'TYPE_RADARCHART', 'addChart', 'setIncludeCharts(TRUE)'] as $literal) m10_check(strpos($controller, $literal) !== FALSE, 'XLSX radar export contract missing: ' . $literal);
m10_check(strpos($controller, "->setTitle('Laporan SPMI')") !== FALSE && strpos($controller, 'setSheetState(\PhpOffice\PhpSpreadsheet\Worksheet\Worksheet::SHEETSTATE_HIDDEN)') !== FALSE, 'XLSX radar export must keep the report sheet visible and hide its chart source sheet.');
m10_check(strpos($controller, 'new \PhpOffice\PhpSpreadsheet\Chart\DataSeriesValues') !== FALSE && strpos($controller, 'new \PhpOffice\PhpSpreadsheet\Chart\Chart') !== FALSE, 'XLSX radar export must use native PhpSpreadsheet chart objects.');
foreach (['https://cdn.jsdelivr.net/npm/chart.js', '$radar_labels', '$radar_values', '$item->indicator_code_snapshot', '(int) $item->score', 'type: \'radar\'', 'r: { min: 0, max: 4', 'stepSize: 1', 'legend: { display: false }', 'tension: 0', 'JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT', 'requestAnimationFrame', 'function printReport()', 'animation: false'] as $literal) m10_check(strpos($print, $literal) !== FALSE, 'Print radar contract missing: ' . $literal);
m10_check(strpos($print, 'onclick="window.print()"') === FALSE && strpos($print, 'aria-label="Radar capaian indikator') !== FALSE, 'Print radar must be accessible and wait through its named print handler.');
foreach (['Laporan.php', 'Laporan_model.php', 'tugas_audit', 'jawaban_audit', 'pdf'] as $legacy) m10_check(strpos($model . $service . $controller . $index . $detail . $print, $legacy) === FALSE, 'M10 legacy isolation broken: ' . $legacy);

foreach (['finding_type_snapshot', 'evidence_url_snapshot', 'evidence_file_original_name_snapshot', 'evidence_file_mime_type_snapshot', 'evidence_file_size_bytes_snapshot', 'evidence_file_sha256_snapshot'] as $field) m10_check(strpos($schema, '`' . $field . '`') !== FALSE, 'M17-06 schema snapshot field missing: ' . $field);
m10_check(strpos($service, "['submitted', 'resubmitted']") !== FALSE || strpos($service, '[\'submitted\', \'resubmitted\']') !== FALSE, 'M17-06 report generation must accept submitted and resubmitted final submissions.');
foreach (['finding_type_snapshot', 'evidence_url_snapshot', 'evidence_file_original_name_snapshot', 'evidence_file_mime_type_snapshot', 'evidence_file_size_bytes_snapshot', 'evidence_file_sha256_snapshot'] as $field) m10_check(strpos($service, "'" . $field . "'") !== FALSE, 'M17-06 generate must persist report item snapshot: ' . $field);
m10_check(strpos($model, 'submission_items_for_report') !== FALSE && strpos($model, 'spmi_auditee_submission_items') !== FALSE && strpos($model, 'spmi_auditee_evidence') !== FALSE, 'M17-06 report model must join locked submission item/evidence source data.');
m10_check(preg_match('/ORDER BY\s+e\.id\s+ASC/i', $model) || preg_match('/MIN\(e2\.id\)/i', $model) || preg_match('/order_by\(\s*[\'\"]e\.id[\'\"]\s*,\s*[\'\"]ASC[\'\"]/i', $model), 'M17-06 report evidence selection must choose one deterministic evidence row.');
foreach (['report_item_evidence', 'spmi_report_item_evidence', 'evidence_for_read', 'private_storage_path', 'stored_name'] as $forbidden) m10_check(strpos($model . $service . $controller . $detail . $print, $forbidden) === FALSE, 'M17-06 reports must not add per-file schema or live-read evidence output: ' . $forbidden);
foreach (['finding_type_snapshot', 'evidence_url_snapshot', 'evidence_file_original_name_snapshot', 'evidence_file_mime_type_snapshot', 'evidence_file_size_bytes_snapshot', 'evidence_file_sha256_snapshot'] as $field) m10_check(strpos($detail, '$item->' . $field) !== FALSE && strpos($print, '$item->' . $field) !== FALSE && strpos($detail, 'html_escape') !== FALSE && strpos($print, 'html_escape') !== FALSE, 'M17-06 detail/print must safely consume item snapshot field: ' . $field);
m10_check(substr_count($detail, 'FILTER_VALIDATE_URL') >= 2 && substr_count($detail, "in_array(\$url_scheme, ['http', 'https'], TRUE)") >= 2, 'Report detail must validate HTTP/HTTPS evidence URLs in desktop and mobile renderers.');
m10_check(substr_count($detail, 'if ($url_is_safe):') >= 2 && substr_count($detail, 'href="<?php echo html_escape($url); ?>"') >= 2, 'Report detail must render evidence anchors only after URL safety validation.');
foreach (['finding_type_snapshot', 'evidence_url_snapshot', 'evidence_file_original_name_snapshot', 'evidence_file_mime_type_snapshot', 'evidence_file_size_bytes_snapshot', 'evidence_file_sha256_snapshot'] as $field) m10_check(strpos($controller, '$item->' . $field) !== FALSE, 'M17-06 export must consume item snapshot field: ' . $field);
foreach (['spmi_reports', 'spmi_report_items'] as $literal) m10_check(strpos(m10_source('application/models/Spmi_rtm_model.php') . m10_source('application/services/Spmi_rtm_service.php'), $literal) !== FALSE, 'M17-06 RTM must remain linked to report snapshots: ' . $literal);

m10_check(preg_match('/finalized_assessments\(\).*spmi_auditee_submissions s.*s\.assignment_id = a\.id.*aa\.source_submission_version = s\.version/s', $model) === 1, 'M17-07B finalized assessment list must require current submission provenance match.');
m10_check(preg_match('/assessment_for_update\(\$assessment_id\).*JOIN spmi_auditee_submissions s ON s\.assignment_id = a\.id AND s\.version = aa\.source_submission_version/s', $model) === 1, 'M17-07B report assessment lock must include matching source_submission_version.');
m10_check(preg_match('/submission_for_update\(\$assignment_id, \$source_submission_version\).*version = \?/s', $model) === 1, 'M17-07B report submission lock must select exact assessment source submission version.');
m10_check(preg_match('/\$this->model->submission_for_update\(\$assignment->id, \$final_assessment->source_submission_version\)/', $service) === 1, 'M17-07B version report generation must load every assessment submission matching its provenance.');
m10_check(preg_match('/\(int\) \$final_assessment->source_submission_version\s*!==\s*\(int\) \$submission->version/', $service) === 1, 'M17-07B version report generation must reject finalized assessment when submission provenance mismatches.');

foreach (['spmi_auditor_assessment_evidence', 'auditor_evidence_snapshot', 'INFORMATION_SCHEMA.COLUMNS'] as $literal) m10_check(strpos($auditor_evidence_migration, $literal) !== FALSE, 'M17-07B report migration contract missing: ' . $literal);
m10_check(strpos($schema, '`auditor_evidence_snapshot` TEXT NULL') !== FALSE, 'M17-07B report snapshot column missing from canonical schema.');
foreach (['auditor_evidence_for_report', 'spmi_auditor_assessment_evidence', 'ORDER BY id ASC', 'FOR UPDATE'] as $literal) m10_check(strpos($model, $literal) !== FALSE, 'M17-07B report model auditor evidence snapshot lock missing: ' . $literal);
foreach (['auditor_evidence_for_report', 'auditor_evidence_snapshot', "'original_name'", "'mime_type'", "'size_bytes'", "'sha256'", 'json_encode'] as $literal) m10_check(strpos($service, $literal) !== FALSE, 'M17-07B report service metadata-only snapshot missing: ' . $literal);
foreach ([$detail, $print, $final_result, $controller] as $surface) m10_check(strpos($surface, 'auditor_evidence_snapshot') !== FALSE, 'M17-07B report surface must consume auditor evidence snapshot.');
foreach ([$detail, $print, $final_result] as $surface) m10_check(strpos($surface, 'json_decode') !== FALSE && strpos($surface, 'html_escape') !== FALSE, 'M17-07B report evidence metadata rendering must JSON-decode with escaped fallback.');
m10_check(strpos($model . $service . $controller . $detail . $print . $final_result, 'stored_name') === FALSE, 'M17-07B reports must not expose stored evidence names.');
m10_check(strpos($controller, 'auditor_evidence_text') !== FALSE && strpos($controller, 'json_decode') !== FALSE && strpos($controller, "'original_name'") !== FALSE && strpos($controller, "'mime_type'") !== FALSE && strpos($controller, "'size_bytes'") !== FALSE && strpos($controller, "'sha256'") !== FALSE, 'M17-07B XLSX export must format auditor evidence snapshot metadata.');
m10_check(strpos($controller, "'K' . \$row, \$this->auditor_evidence_text") !== FALSE && strpos($controller, "'K' . \$row, isset(\$item->auditor_evidence_snapshot)") === FALSE, 'M17-07B XLSX export must not write raw auditor evidence JSON.');
foreach (['improvement_plan_snapshot', 'evidence_date_snapshot'] as $field) m10_check(strpos($schema, '`' . $field . '`') !== FALSE && strpos($service, "'" . $field . "'") !== FALSE && strpos($detail, '$item->' . $field) !== FALSE && strpos($print, '$item->' . $field) !== FALSE && strpos($controller, '$item->' . $field) !== FALSE, 'M17-07C report snapshot must persist and render: ' . $field);
m10_check(strpos($controller . $detail . $print . $final_result, 'spmi_auditor_assessment_items') === FALSE, 'M17-07C report read surfaces must not read live assessment items.');
foreach (['auditor_id_snapshot', 'auditor_name_snapshot', 'auditor_email_snapshot'] as $field) m10_check(strpos($service, "'" . $field . "'") !== FALSE, 'Version-auditee report must persist item auditor snapshot: ' . $field);
foreach (['auditor_name_snapshot', 'auditor_email_snapshot'] as $field) m10_check(strpos($detail . $print . $word . $controller, $field) !== FALSE, 'Version-auditee report must consume item auditor snapshot: ' . $field);
m10_check(strpos($word, 'spmi_') === FALSE && strpos($word, 'html_escape') !== FALSE && strpos($controller, "Content-Type: application/msword; charset=UTF-8") !== FALSE && strpos($controller, '"\\xEF\\xBB\\xBF"') !== FALSE, 'Word export must be UTF-8 HTML over the immutable report payload only.');
m10_check(strpos($controller, "'items' => $" . "data['items']") !== FALSE, 'Word export must hand immutable report items into the template.');
foreach (['word-radar-capaian-indikator', 'data:image/png;base64,', '<img', 'imagecreatetruecolor', 'imagepolygon', 'imagefilledpolygon', 'imagepng', 'base64_encode', 'imagestring', 'Radar Capaian Indikator', 'Radar capaian indikator SPMI skala 0 sampai 4', 'Skor snapshot (0..4)'] as $literal) m10_check(strpos($word, $literal) !== FALSE, 'Word GD radar marker missing: ' . $literal);
m10_check(strpos($word, 'for ($level = 1; $level <= 4; $level++)') !== FALSE && strpos($word, 'max(0, min(4, (float) $item->score))') !== FALSE && strpos($word, 'max(0, min(4, $value)) / 4') !== FALSE && strpos($word, 'imagedestroy($radar_image)') !== FALSE, 'Word radar geometry must be defensively clamped to the immutable 0..4 scale and release GD resources.');
$word_radar_setup = substr($word, 0, strpos($word, '<!DOCTYPE html>'));
m10_check(strpos($word_radar_setup, '$item->indicator_code_snapshot') !== FALSE && strpos($word_radar_setup, '$item->score') !== FALSE && strpos($word_radar_setup, 'indicator_title_snapshot') === FALSE, 'Word radar labels/scores must use immutable indicator code snapshots and item scores.');
m10_check(strpos($word, '<table class="radar-legend">') !== FALSE && strpos($word, 'html_escape($radar_item[\'label\'])') !== FALSE && strpos($word, 'html_escape((string) $radar_item[\'score\'])') !== FALSE, 'Word radar must include a visible escaped HTML fallback score legend.');
m10_check(strpos($word, '<?php if ($radar_count > 0): ?>') !== FALSE && strpos($word, '<?php foreach ($standards as $standard): ?>') !== FALSE && strpos($word, '<?php if ($radar_count > 0): ?>') < strpos($word, '<?php foreach ($standards as $standard): ?>'), 'Word radar must render only for immutable items and appear before report tables.');
foreach (['<script', 'Chart.js', 'new Chart', '<canvas', '<svg', '<v:', 'cdn.', 'http://', 'https://', 'file://', 'data:text', 'data:image/svg'] as $forbidden) m10_check(stripos($word, $forbidden) === FALSE, 'Word export must not depend on browser/chart assets: ' . $forbidden);

fwrite(STDOUT, "SPMI reports regression checks passed.\n");
