<?php
$root = dirname(__DIR__);
function m9_source($path) { $value = file_get_contents(dirname(__DIR__) . DIRECTORY_SEPARATOR . $path); if ($value === FALSE) throw new RuntimeException('Tidak dapat membaca ' . $path); return $value; }
function m9_check($condition, $message) { if (!$condition) throw new RuntimeException($message); }

$migration = m9_source('migrations/019_create_spmi_auditor_workspace.sql');
$schema = m9_source('database_schema.sql');
$model = m9_source('application/models/Spmi_auditor_workspace_model.php');
$service = m9_source('application/services/Spmi_auditor_workspace_service.php');
$controller = m9_source('application/controllers/Spmi_auditor_workspace.php');
$routes = m9_source('application/config/routes.php');
$sidebar = m9_source('application/views/layouts/sidebar.php');
$index = m9_source('application/views/spmi_auditor_workspace/index.php');
$assignment = m9_source('application/views/spmi_auditor_workspace/assignment.php');
$auditor_evidence_migration = m9_source('migrations/029_add_spmi_auditor_assessment_evidence.sql');

foreach (['spmi_auditor_assessments', 'spmi_auditor_assessment_items', "ENUM('draft','finalized')", 'finalized_at', 'realization_snapshot', 'finding', 'recommendation', 'UNIQUE KEY', 'ON DELETE RESTRICT'] as $literal) m9_check(strpos($migration, $literal) !== FALSE, 'M9 migration contract missing: ' . $literal);
m9_check(strpos($migration, 'INSERT') === FALSE, 'M9 migration must be seed-free.');
foreach (['current parity migration 001-030', 'spmi_auditor_assessments', 'spmi_auditor_assessment_items', 'uq_spmi_auditor_assessments_assignment_source_version', 'uq_spmi_auditor_assessment_items_item', 'idx_spmi_auditor_assessment_items_item'] as $literal) m9_check(strpos($schema, $literal) !== FALSE, 'M9 schema parity missing: ' . $literal);
foreach (['a.auditor_id', 'c.state IN (?, ?)', 'assignment_items($assignment_id, $user_id)', 'rubrics($item_id, $user_id)', 'cycle_for_update', 'submission_for_update', 'assessment_for_update', 'assessment_items_for_update', 'FOR UPDATE', 'submitted', 'closed'] as $literal) m9_check(strpos($model, $literal) !== FALSE, 'M9 ownership/lock contract missing: ' . $literal);
foreach (['trans_begin', 'state !== \'configured\'', 'status !== \'submitted\'', 'status !== \'draft\'', 'CONFLICT', 'realization_snapshot', 'raw_score', '!is_string($raw_score)', "in_array(\$raw_score, ['1', '2', '3', '4'], TRUE)", 'Skor wajib kosong atau bernilai 1 sampai 4.', 'finalize', 'affected_rows() !== 1', 'private_storage_path', 'audit_evidence'] as $literal) m9_check(strpos($service, $literal) !== FALSE, 'M9 service lifecycle contract missing: ' . $literal);
m9_check(strpos($service, "(int) \$value['score']") === FALSE && strpos($service, 'is_array($raw_score)') === FALSE, 'M9 score validation must inspect raw scalar string before conversion.');
foreach (['extends CI_Controller', 'auth_guard->only([\'auditor\'])', "method(TRUE) !== 'POST'", 'Spmi_auditor_workspace_service', 'Cache-Control: private, no-store', 'Expires: 0'] as $literal) m9_check(strpos($controller, $literal) !== FALSE, 'M9 controller contract missing: ' . $literal);
foreach (['auditor/spmi\'', 'assignment/(:num)', 'assignment/(:num)/save', 'assignment/(:num)/finalize', 'evidence/(:num)/download'] as $literal) m9_check(strpos($routes, $literal) !== FALSE, 'M9 route missing: ' . $literal);
m9_check(substr_count($sidebar, "'key' => 'spmi_assessment', 'label' => 'Penilaian SPMI', 'icon' => 'fa-clipboard-check', 'url' => 'auditor/spmi', 'group' => 'Work'") === 1, 'M9 sidebar entry must be auditor-only.');
m9_check(substr_count($assignment, 'form_open(') >= 1 && strpos($assignment, 'name="version"') !== FALSE && strpos($assignment, 'formaction=') !== FALSE, 'M9 assessment form contract missing.');
m9_check(substr_count($assignment, 'html_escape') >= 8 && strpos($assignment, 'rubrics') !== FALSE && strpos($assignment, 'realization_snapshot') !== FALSE, 'M9 immutable M7/M8 view data missing.');
foreach (['Auditor.php', 'Auditor_service.php', 'Jawaban_model', 'tugas_audit', 'jawaban_audit', 'bukti_auditor', 'auditor/penilaian', 'auditor/tugas'] as $legacy) m9_check(strpos($model . $service . $controller . $index . $assignment, $legacy) === FALSE, 'M9 legacy isolation broken: ' . $legacy);

m9_check(strpos($routes, 'auditor/spmi/assignment/(:num)/return') !== FALSE, 'M17-04 auditor return-for-revision POST route missing.');
m9_check(strpos($controller, 'public function return_for_revision(') !== FALSE && strpos($controller, "method(TRUE) !== 'POST'") !== FALSE && strpos($controller, "post('reason'") !== FALSE, 'M17-04 auditor return-for-revision POST action with mandatory reason missing.');
m9_check(strpos($service, 'return_for_revision') !== FALSE && strpos($service, 'trim($reason)') !== FALSE && strpos($service, "status !== 'submitted'") !== FALSE && strpos($service, "status !== 'resubmitted'") !== FALSE, 'M17-04 submitted or resubmitted to returned_for_revision transition missing.');
m9_check(strpos($service, "'status' => 'returned_for_revision'") !== FALSE && strpos($service, 'source_submission_version') !== FALSE && strpos($service, 'actor') !== FALSE && strpos($service, 'reason') !== FALSE, 'M17-04 return event must capture actor status version and reason.');
m9_check(strpos($model, 'revision_history') !== FALSE && strpos($model, 'a.auditor_id') !== FALSE && strpos($model, 'spmi_auditee_submission_revision_events') !== FALSE, 'M17-04 ownership-scoped immutable revision history read missing for auditor.');
$assessment_mutation_service = substr($service, 0, strpos($service, 'public function upload_auditor_evidence'));
m9_check(strpos($assessment_mutation_service, 'source_submission_version') !== FALSE && strpos($assessment_mutation_service, 'delete') === FALSE && strpos($assessment_mutation_service, 'reset') === FALSE && preg_match('/source_submission_version.{0,400}(CONFLICT|STALE|stale|versi)/s', $assessment_mutation_service), 'M17-04 stale assessment draft rejection using source_submission_version without deletion/reset missing.');
m9_check(strpos($model, 'create_assessment($assignment_id, $source_submission_version)') !== FALSE && strpos($model, "'source_submission_version' => (int) $" . 'source_submission_version') !== FALSE && strpos($service, 'create_assessment($assignment->id, $submission->version)') !== FALSE, 'M17-04 create path must bind assessment draft to locked submission source version.');
m9_check(preg_match('/source_submission_version\s*!==\s*NULL.{0,220}source_submission_version.{0,120}submission->version.{0,120}CONFLICT/s', $service), 'M17-04 stale save/finalize guard must compare source_submission_version to live submission version.');
m9_check(preg_match('/source_submission_version\s*===\s*NULL\s*&&\s*\$submission->status\s*===\s*\'resubmitted\'.{0,120}CONFLICT/s', $service) && preg_match('/source_submission_version\s*!==\s*NULL\s*&&\s*\(int\)\s*\$assessment->source_submission_version\s*!==\s*\(int\)\s*\$submission->version.{0,120}CONFLICT/s', $service), 'M17-04 stale guard must reject bound mismatches and unbound legacy drafts only after resubmitted.');

m9_check(preg_match('/join\(\'spmi_auditor_assessments aa\', \'aa\.assignment_id = a\.id AND aa\.source_submission_version = s\.version\', \'left\'\)/', $model) === 1, 'M17-07B assignments list must join assessment by assignment and current submission version.');
m9_check(preg_match('/LEFT JOIN spmi_auditor_assessments aa ON aa\.assignment_id = a\.id AND aa\.source_submission_version = s\.version/', $model) === 1, 'M17-07B assignment detail must select assessment for current submission version only.');
m9_check(preg_match('/assessment_for_update\(\$assignment_id, \$user_id, \$source_submission_version\).*aa\.source_submission_version = \?/s', $model) === 1, 'M17-07B assessment lock must include source_submission_version identity.');
m9_check(preg_match('/assessment\(\$assignment_id, \$user_id, \$source_submission_version\).*aa\.source_submission_version.{0,160}\$source_submission_version/s', $model) === 1, 'M17-07B assessment read must include source_submission_version identity.');
m9_check(preg_match('/\$this->model->assessment_for_update\(\$assignment->id, \$user_id, \$submission->version\)/', $service) === 1, 'M17-07B create guard must look for current-version assessment, not any old assignment draft.');
m9_check(preg_match('/\$this->model->assessment\(\$assignment_id, \$user_id, \$assignment->submission_version\)/', $service) === 1, 'M17-07B workspace must bind displayed assessment to current submission version.');
m9_check(preg_match_all('/\$this->model->assessment_for_update\(\$assignment->id, \$user_id, \$submission->version\)/', $service) >= 2, 'M17-07B save/finalize/return paths must lock current-version assessment so old drafts stay unmodified/nonfinalizable.');

m9_check(preg_match('/<input\s+type="hidden"\s+name="source_submission_version"\s+value="<\?php\s+echo\s+html_escape\(\(string\)\s+\$assignment->submission_version\);\s+\?>">/', $assignment) === 1, 'M17-07C auditor assessment form must submit hidden source_submission_version from locked live submission version.');
m9_check(preg_match('/\$this->service->\$method\(\(int\)\s+\$id,\s*\$this->user_id\(\),\s*\$this->post_int\(\'version\'\),\s*\$this->post_int\(\'source_submission_version\'\),\s*\$this->input->post\(\'assessment\',\s*TRUE\)\)/s', $controller) === 1 && strpos($controller, "post_int('source_submission_version')") !== FALSE && strpos($controller, 'ctype_digit((string) $value)') !== FALSE, 'M17-07C auditor controller save/finalize must validate and pass posted source_submission_version into service mutation.');
m9_check(preg_match('/public\s+function\s+save\(\$assignment_id,\s*\$user_id,\s*\$version,\s*\$source_submission_version,\s*\$values\)/', $service) === 1 && preg_match('/public\s+function\s+finalize\(\$assignment_id,\s*\$user_id,\s*\$version,\s*\$source_submission_version,\s*\$values\)/', $service) === 1 && preg_match('/protected\s+function\s+mutate\(\$assignment_id,\s*\$user_id,\s*\$version,\s*\$source_submission_version,\s*\$values,\s*\$finalize\)/', $service) === 1, 'M17-07C service save/finalize/mutate signatures must carry posted source_submission_version.');
m9_check(strpos($service, 'valid_int($source_submission_version)') !== FALSE && preg_match('/\(int\)\s+\$source_submission_version\s*!==\s*\(int\)\s+\$submission->version.{0,160}CONFLICT/s', $service) === 1, 'M17-07C service mutate must reject invalid or stale posted source_submission_version when it differs from locked live submission version.');

foreach (["post('assessment', TRUE)", '$this->service->$method'] as $literal) m9_check(strpos($controller, $literal) !== FALSE, 'M17-05 controller must pass nested assessment payload to service: ' . $literal);
$legacy_controller = substr($controller, 0, strpos($controller, 'public function save_item('));
m9_check(strpos($legacy_controller, "post('finding_type'") === FALSE && strpos($legacy_controller, 'finding_type_by_item') === FALSE, 'M17-05 controller must not invent a separate finding_type API.');
foreach (['finding_type', 'raw_finding_type', "in_array($" . "raw_finding_type, ['ob', 'kts'], TRUE)", '$finding_type = NULL', "'finding_type' => $" . "finding_type"] as $literal) m9_check(strpos($service, $literal) !== FALSE, 'M17-05 service finding_type normalization/allowlist contract missing: ' . $literal);
m9_check(preg_match('/finalize.{0,600}score.{0,300}(finding_type|raw_finding_type).{0,260}(finding|raw_finding).{0,260}(recommendation|raw_recommendation)/s', $service), 'M17-05 finalize must validate score, OB/KTS finding, and KTS recommendation in one server-side branch.');
m9_check(preg_match('/(finding_type|raw_finding_type).{0,140}(ob|kts).{0,180}(finding|raw_finding).{0,180}(wajib|required|harus|empty\()/is', $service), 'M17-05 OB/KTS finalization must reject missing finding.');
m9_check(preg_match('/(finding_type|raw_finding_type).{0,80}kts.{0,220}(recommendation|raw_recommendation).{0,180}(wajib|required|harus|empty\()/is', $service), 'M17-05 KTS finalization must reject missing recommendation.');
m9_check(preg_match('/raw_score.{0,260}NULL.{0,900}finding_type/s', $service), 'M17-05 draft saves must remain partial while accepting finding_type.');
foreach (['finding_type', "'finding_type'", 'update_item'] as $literal) m9_check(strpos($model . $service, $literal) !== FALSE, 'M17-05 model finding_type persistence contract missing: ' . $literal);
m9_check(strpos($model, 'spmi_auditor_assessment_items.finding_type') !== FALSE || preg_match('/assessment_items.{0,400}ai\.\*/s', $model), 'M17-05 assessment item reads must include finding_type through ai.*.');
foreach (['[finding_type]', 'value=""', 'value="ob"', 'value="kts"', 'html_escape', 'readonly', 'disabled'] as $literal) m9_check(strpos($assignment, $literal) !== FALSE, 'M17-05 view controlled/read-only/escaped finding_type contract missing: ' . $literal);
m9_check(strpos($assignment . $service . $model, 'action_plan') === FALSE, 'M17-05 must not add legacy action_plan behavior.');

foreach (['spmi_audit_assignments a', 'spmi_auditee_submissions s', 'spmi_auditee_submission_items si', 'spmi_audit_assignment_items i'] as $literal) m9_check(strpos($model, $literal) !== FALSE, 'M17-05A auditor evidence URL source chain missing: ' . $literal);
m9_check(preg_match('/assignment_items\(\$assignment_id, \$user_id\).*select\(\'i\.\*, si\.evidence_url\'\).*from\(\'spmi_audit_assignment_items i\'\).*join\(\'spmi_audit_assignments a\', \'a\.id = i\.assignment_id\'\).*join\(\'spmi_auditee_submissions s\', \'s\.assignment_id = a\.id\'\).*join\(\'spmi_auditee_submission_items si\', \'si\.submission_id = s\.id AND si\.assignment_item_id = i\.id\'\)/s', $model) === 1, 'M17-05A assignment_items must select URL through assignment submission item ownership chain.');
m9_check(preg_match('/assignment_items\(\$assignment_id, \$user_id\).*where\(\'a\.id\', \(int\) \$assignment_id\).*where\(\'a\.auditor_id\', \(int\) \$user_id\).*where_in\(\'s\.status\', \[\'submitted\', \'resubmitted\', \'returned_for_revision\'\]\).*order_by\(\'i\.display_order\', \'ASC\'\)/s', $model) === 1, 'M17-05A assignment_items must filter exact assignment, auditor ownership, readable status, and preserve order.');
m9_check(strpos($model, 'si.evidence_url') !== FALSE, 'M17-05A auditor evidence URL query must select si.evidence_url.');
foreach (['a.auditor_id', 'a.id', 'i.assignment_id', 's.status', 'submitted', 'resubmitted'] as $literal) m9_check(strpos($model, $literal) !== FALSE, 'M17-05A auditor evidence URL owner/status constraint missing: ' . $literal);
foreach (['evidence_url', 'filter_var', 'FILTER_VALIDATE_URL', 'parse_url', 'PHP_URL_SCHEME', "['http', 'https']", 'html_escape', 'target="_blank"', 'rel="noopener noreferrer"'] as $literal) m9_check(strpos($assignment, $literal) !== FALSE, 'M17-05A safe auditor evidence URL view contract missing: ' . $literal);
m9_check(preg_match('/evidence_url\s*={2,3}\s*\'\'.{0,220}(text-muted|Tidak ada|Belum ada|-)/s', $assignment) === 1, 'M17-05A empty evidence URL must render a neutral non-clickable marker.');
m9_check(preg_match('/filter_var\([^,]+,\s*FILTER_VALIDATE_URL\)/', $assignment) === 1, 'M17-05A evidence URL validation must use filter_var URL validation.');
m9_check(preg_match('/parse_url\([^,]+,\s*PHP_URL_SCHEME\)/', $assignment) === 1, 'M17-05A evidence URL scheme extraction must use parse_url PHP_URL_SCHEME.');
m9_check(strpos($assignment, "['http', 'https']") !== FALSE && strpos($assignment, "['https', 'http']") === FALSE, 'M17-05A evidence URL scheme allowlist must be exactly http/https in that order.');
m9_check(preg_match('/<a\b[^>]*href="<\?php\s+echo\s+html_escape\([^)]*evidence_url[^)]*\);\s*\?>"[^>]*target="_blank"[^>]*rel="noopener noreferrer"/s', $assignment) === 1, 'M17-05A safe evidence URL link must escape href and open with noopener noreferrer.');
m9_check(substr_count($assignment, 'html_escape($evidence_url)') >= 2, 'M17-05A safe evidence URL link must escape href and display text.');
m9_check(preg_match('/else\s*:\s*.{0,220}(tidak valid|invalid|text-muted)/is', $assignment) === 1, 'M17-05A unsafe evidence URL schemes must render a neutral non-clickable state.');
m9_check(strpos($assignment, 'site_url(\'auditor/spmi/evidence/\' . (int) $evidence->id . \'/download\')') !== FALSE && strpos($assignment, 'realization_snapshot') !== FALSE, 'M17-05A realization/file download display must remain preserved beside URL evidence.');

foreach (['spmi_auditor_assessment_evidence', 'assessment_item_id', 'stored_name', 'original_name', 'mime_type', 'size_bytes', 'sha256', 'ON DELETE RESTRICT', 'auditor_evidence_snapshot'] as $literal) m9_check(strpos($auditor_evidence_migration, $literal) !== FALSE, 'M17-07B auditor evidence migration missing: ' . $literal);
foreach (['auditor_evidence', 'lock_auditor_evidence_count', 'assessment_item_for_update', 'auditor_evidence_for_update', 'auditor_evidence_for_read', 'add_auditor_evidence', 'delete_auditor_evidence', 'a.auditor_id', 'FOR UPDATE'] as $literal) m9_check(strpos($model, $literal) !== FALSE, 'M17-07B auditor evidence model contract missing: ' . $literal);
foreach (['upload_auditor_evidence', 'delete_auditor_evidence', 'download_auditor_evidence', 'finfo_open', 'getimagesize', '5 * 1024 * 1024', 'random_bytes', 'bin2hex', 'hash_file', 'lock_auditor_evidence_count', 'source_submission_version', 'update_assessment', 'cleanup_paths'] as $literal) m9_check(strpos($service, $literal) !== FALSE, 'M17-07B auditor evidence service contract missing: ' . $literal);
foreach (['upload_auditor_evidence', 'delete_auditor_evidence', 'download_auditor_evidence', "method(TRUE) !== 'POST'", 'post_int(\'version\')', 'post_int(\'source_submission_version\')'] as $literal) m9_check(strpos($controller, $literal) !== FALSE, 'M17-07B auditor evidence controller contract missing: ' . $literal);
foreach (['assessment-item/(:num)/evidence/upload', 'auditor-evidence/(:num)/delete', 'auditor-evidence/(:num)/download'] as $literal) m9_check(strpos($routes, $literal) !== FALSE, 'M17-07B auditor evidence route missing: ' . $literal);
foreach (['Bukti auditee', 'Bukti auditor', 'form_open_multipart', 'auditor_evidence', 'source_submission_version', 'accept="application/pdf,image/jpeg,image/png"', 'html_escape'] as $literal) m9_check(strpos($assignment, $literal) !== FALSE, 'M17-07B auditor evidence view contract missing: ' . $literal);
m9_check(preg_match('/form_open\(\'auditor\/spmi\/assignment\/.*?form_close\(\);/s', $assignment) === 1, 'M17-07B assessment save form must be singular and close before independent evidence forms.');
m9_check(strpos($assignment, 'form_open_multipart') < strpos($assignment, "form_open('auditor/spmi/assignment/"), 'M17-07B upload forms must precede, not nest in, assessment save form.');

foreach (['improvement_plan', 'evidence_date', 'Rencana perbaikan', 'Tanggal bukti', 'html_escape'] as $literal) m9_check(strpos($assignment, $literal) !== FALSE, 'M17-07C auditor form field missing: ' . $literal);
foreach (['improvement_plan', 'evidence_date', "'improvement_plan' => $" . 'improvement_plan', "'evidence_date' => $" . 'evidence_date', 'protected function date'] as $literal) m9_check(strpos($service, $literal) !== FALSE, 'M17-07C auditor persistence contract missing: ' . $literal);
m9_check(preg_match('/\$finalize\s*&&\s*\$finding_type\s*===\s*\'kts\'.{0,160}\$improvement_plan\s*===\s*NULL/s', $service) === 1, 'M17-07C KTS finalization must require improvement plan.');
m9_check(strpos($service, 'Tanggal bukti tidak valid.') !== FALSE && strpos($service, '!is_string($value[$key])') !== FALSE, 'M17-07C evidence date must be optional and scalar-safe.');

m9_check(strpos($routes, 'auditor/spmi/item/(:num)/save') !== FALSE, 'M17-07D auditor item autosave route missing.');
m9_check(preg_match('/public\s+function\s+save_item\(\$id\)/', $controller) === 1 && strpos($controller, "method(TRUE) !== 'POST'") !== FALSE && strpos($controller, 'application/json') !== FALSE && strpos($controller, 'save_item((int) $id') !== FALSE, 'M17-07D auditor controller must expose POST JSON save_item endpoint.');
m9_check(strpos($controller, "post_int('version')") !== FALSE && strpos($controller, "post_int('source_submission_version')") !== FALSE && preg_match('/foreach\s*\(\[\'score\', \'finding_type\', \'finding\', \'recommendation\', \'improvement_plan\', \'evidence_date\'\].*?post\(\$field, TRUE\)/s', $controller) === 1, 'M17-07D auditor controller must read autosave payload fields and version inputs.');
m9_check(preg_match('/public\s+function\s+save_item\(\$assessment_item_id,\s*\$user_id,\s*\$version,\s*\$source_submission_version,\s*\$value\)/', $service) === 1, 'M17-07D auditor service save_item signature missing.');
m9_check(strpos($service, 'trans_begin') !== FALSE && strpos($service, 'assessment_item_autosave_for_update') !== FALSE && strpos($service, 'source_submission_version') !== FALSE && strpos($service, "state !== 'configured'") !== FALSE && preg_match("/submission_status,?\s*\['submitted', 'resubmitted'\]/", $service) === 1 && strpos($service, "assessment_status !== 'draft'") !== FALSE && strpos($service, 'update_item') !== FALSE && strpos($service, 'update_assessment') !== FALSE && strpos($service, 'affected_rows() !== 1') !== FALSE, 'M17-07D auditor autosave service must enforce transaction ownership state and optimistic version update.');
m9_check(strpos($service, "'score' =>") !== FALSE && strpos($service, "'finding_type' =>") !== FALSE && strpos($service, "'finding' =>") !== FALSE && strpos($service, "'recommendation' =>") !== FALSE && strpos($service, "'improvement_plan' =>") !== FALSE && strpos($service, "'evidence_date' =>") !== FALSE, 'M17-07D auditor autosave service must persist exact payload fields.');
$save_item_service = substr($service, strpos($service, 'public function save_item('), strpos($service, 'public function finalize(') - strpos($service, 'public function save_item('));
m9_check(strpos($service, 'Semua item wajib diberi skor 1 sampai 4 sebelum finalisasi.') !== FALSE && strpos($save_item_service, 'Semua item wajib diberi skor 1 sampai 4 sebelum finalisasi.') === FALSE, 'M17-07D autosave must not require finalization completeness.');
$save_item_success = substr($service, strpos($service, 'public function save_item('), strpos($service, 'public function finalize(') - strpos($service, 'public function save_item('));
m9_check(strpos($save_item_success, "'success' => TRUE") !== FALSE && strpos($save_item_success, "'message' => " . '$result[' . "'message']") !== FALSE && strpos($save_item_success, "'version' => (int) " . '$version' . ' + 1') !== FALSE, 'M17-07D autosave success JSON must return next optimistic version.');
m9_check(preg_match('/public\s+function\s+assessment_item_for_update\(\$assessment_item_id,\s*\$user_id,\s*\$version\).*FOR UPDATE/s', $model) === 1 && strpos($model, 'a.auditor_id') !== FALSE && strpos($model, 'aa.source_submission_version') !== FALSE && strpos($model, 's.version = aa.source_submission_version') !== FALSE, 'M17-07D model lock must preserve owner-scoped source-version item read.');
m9_check(strpos($assignment, 'auditor/spmi/item/') !== FALSE && strpos($assignment, 'fetch(') !== FALSE && strpos($assignment, 'csrf') !== FALSE && strpos($assignment, 'source_submission_version') !== FALSE && strpos($assignment, 'version') !== FALSE && strpos($assignment, 'submitted') !== FALSE && strpos($assignment, 'resubmitted') !== FALSE, 'M17-07D view must wire fetch autosave with CSRF source version version propagation and status indicator.');

foreach (['cycle_id', 'status', "['submitted', 'resubmitted', 'returned_for_revision']", 'source_submission_version = s.version', 'a.auditor_id'] as $literal) m9_check(strpos($model, $literal) !== FALSE, 'M17-07E auditor owned filter query missing: ' . $literal);
m9_check(strpos($model, 'attention_count') !== FALSE && strpos($model, "aa.status IS NULL OR aa.status != 'finalized'") !== FALSE, 'M17-07E auditor badge must count only current submitted/resubmitted work without finalized current-version assessment.');
foreach (['filter', 'cycle_options', 'attention_count', 'menu_badges', 'is_scalar', 'ctype_digit'] as $literal) m9_check(strpos($controller, $literal) !== FALSE, 'M17-07E auditor scalar-safe filter/badge controller contract missing: ' . $literal);
foreach (['cycle_options', 'attention_count', 'assignments($user_id, $filters)', 'filters'] as $literal) m9_check(strpos($service, $literal) !== FALSE, 'M17-07E auditor filter/badge service contract missing: ' . $literal);
foreach (['method="get"', 'name="cycle_id"', 'name="status"', 'site_url(\'auditor/spmi\')', 'html_escape'] as $literal) m9_check(strpos($index, $literal) !== FALSE, 'M17-07E auditor GET filter UI contract missing: ' . $literal);
foreach (['Spmi_auditor_workspace_service', 'attention_count($user_id)', 'spmi_assessment'] as $literal) m9_check(strpos(m9_source('application/controllers/Spmi_auditor_dashboard.php'), $literal) !== FALSE, 'M17-07E auditor dashboard must propagate workspace attention badge: ' . $literal);

fwrite(STDOUT, "SPMI auditor workspace regression checks passed.\n");
