<?php defined('BASEPATH') OR exit('No direct script access allowed'); include APPPATH . 'views/layouts/header.php'; include APPPATH . 'views/layouts/sidebar.php'; ?>
<div class="ami-panel" style="max-width: 680px;"><div class="ami-panel-body"><h2 class="ami-section-title mb-4">Tambah Penempatan</h2>
<?php if (validation_errors()): ?><div class="alert alert-danger"><?php echo validation_errors(); ?></div><?php endif; ?>
<?php echo form_open('lpmpi/organization/assignment/store'); ?>
<div class="form-group"><label for="user_id">Pengguna</label><select class="form-control" id="user_id" name="user_id" required><option value="">Pilih pengguna</option><?php foreach ($users as $user): ?><option value="<?php echo (int) $user->id; ?>" <?php echo set_select('user_id', $user->id); ?>><?php echo html_escape($user->nama . ' (' . $user->email . ')'); ?></option><?php endforeach; ?></select></div>
<div class="form-group"><label for="organization_unit_id">Unit</label><select class="form-control" id="organization_unit_id" name="organization_unit_id" required><option value="">Pilih unit aktif</option><?php foreach ($units as $unit): ?><?php if ((int) $unit->is_active === 1): ?><option value="<?php echo (int) $unit->id; ?>" <?php echo set_select('organization_unit_id', $unit->id); ?>><?php echo html_escape($unit->code . ' - ' . $unit->name); ?></option><?php endif; ?><?php endforeach; ?></select></div>
<div class="form-group"><label for="position_code">Kode Posisi</label><input class="form-control" id="position_code" name="position_code" maxlength="64" value="<?php echo html_escape(set_value('position_code')); ?>" required></div>
<div class="form-row"><div class="form-group col-md-6"><label for="valid_from">Berlaku mulai</label><input class="form-control" type="date" id="valid_from" name="valid_from" value="<?php echo html_escape(set_value('valid_from')); ?>" required></div><div class="form-group col-md-6"><label for="valid_until">Berlaku sampai</label><input class="form-control" type="date" id="valid_until" name="valid_until" value="<?php echo html_escape(set_value('valid_until')); ?>"></div></div>
<div class="form-check mb-4"><input class="form-check-input" type="checkbox" id="is_primary" name="is_primary" value="1" <?php echo set_checkbox('is_primary', '1'); ?>><label class="form-check-label" for="is_primary">Jadikan penempatan utama</label></div>
<div class="d-flex justify-content-end" style="gap: var(--ami-space-sm);"><a class="btn btn-secondary" href="<?php echo site_url('lpmpi/organization'); ?>">Batal</a><button class="btn btn-ami" type="submit">Simpan</button></div>
<?php echo form_close(); ?></div></div>
<?php include APPPATH . 'views/layouts/footer.php'; ?>
