CREATE TABLE IF NOT EXISTS `legacy_ami_archive_runs` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `archive_code` VARCHAR(128) NOT NULL,
    `source_label` VARCHAR(200) NOT NULL,
    `status` ENUM('planned','imported','reconciled','failed') NOT NULL DEFAULT 'planned',
    `legacy_task_count` INT UNSIGNED NOT NULL DEFAULT 0,
    `legacy_answer_count` INT UNSIGNED NOT NULL DEFAULT 0,
    `archived_task_count` INT UNSIGNED NOT NULL DEFAULT 0,
    `archived_answer_count` INT UNSIGNED NOT NULL DEFAULT 0,
    `issue_count` INT UNSIGNED NOT NULL DEFAULT 0,
    `notes` TEXT NULL,
    `created_by_snapshot` VARCHAR(200) NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY `uq_legacy_ami_archive_runs_code` (`archive_code`),
    KEY `idx_legacy_ami_archive_runs_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `legacy_ami_archive_tasks` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `run_id` INT NOT NULL,
    `legacy_tugas_id` INT NOT NULL,
    `legacy_periode_id` INT NULL,
    `legacy_standar_id` INT NULL,
    `legacy_auditor_id` INT NULL,
    `legacy_auditee_id` INT NULL,
    `periode_name_snapshot` VARCHAR(200) NULL,
    `periode_year_snapshot` VARCHAR(20) NULL,
    `periode_semester_snapshot` VARCHAR(20) NULL,
    `standard_name_snapshot` VARCHAR(200) NULL,
    `standard_description_snapshot` TEXT NULL,
    `auditor_name_snapshot` VARCHAR(200) NULL,
    `auditor_email_snapshot` VARCHAR(200) NULL,
    `auditee_name_snapshot` VARCHAR(200) NULL,
    `auditee_email_snapshot` VARCHAR(200) NULL,
    `auditee_unit_snapshot` VARCHAR(200) NULL,
    `auditee_unit_type_snapshot` VARCHAR(64) NULL,
    `legacy_status_snapshot` VARCHAR(64) NOT NULL,
    `legacy_created_at_snapshot` DATETIME NULL,
    `archived_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY `uq_legacy_ami_archive_tasks_legacy` (`run_id`, `legacy_tugas_id`),
    KEY `idx_legacy_ami_archive_tasks_run` (`run_id`),
    CONSTRAINT `fk_legacy_ami_archive_tasks_run` FOREIGN KEY (`run_id`) REFERENCES `legacy_ami_archive_runs` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `legacy_ami_archive_answers` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `archive_task_id` INT NOT NULL,
    `legacy_jawaban_id` INT NOT NULL,
    `legacy_pertanyaan_id` INT NULL,
    `question_order_snapshot` INT NULL,
    `question_text_snapshot` TEXT NULL,
    `question_category_snapshot` VARCHAR(32) NULL,
    `answer_text_snapshot` TEXT NULL,
    `evidence_link_snapshot` VARCHAR(500) NULL,
    `submitted_snapshot` TINYINT(1) NOT NULL DEFAULT 0,
    `submitted_at_snapshot` DATETIME NULL,
    `score_snapshot` INT NULL,
    `finding_snapshot` TEXT NULL,
    `finding_type_snapshot` VARCHAR(32) NULL,
    `recommendation_snapshot` TEXT NULL,
    `improvement_plan_snapshot` TEXT NULL,
    `evidence_document_name_snapshot` VARCHAR(255) NULL,
    `evidence_date_snapshot` DATE NULL,
    `assessment_submitted_snapshot` TINYINT(1) NOT NULL DEFAULT 0,
    `assessment_submitted_at_snapshot` DATETIME NULL,
    `archived_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY `uq_legacy_ami_archive_answers_legacy` (`archive_task_id`, `legacy_jawaban_id`),
    KEY `idx_legacy_ami_archive_answers_task` (`archive_task_id`),
    CONSTRAINT `fk_legacy_ami_archive_answers_task` FOREIGN KEY (`archive_task_id`) REFERENCES `legacy_ami_archive_tasks` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `legacy_ami_archive_issues` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `run_id` INT NOT NULL,
    `archive_task_id` INT NULL,
    `archive_answer_id` INT NULL,
    `severity` ENUM('info','warning','error') NOT NULL DEFAULT 'warning',
    `issue_code` VARCHAR(128) NOT NULL,
    `message` TEXT NOT NULL,
    `legacy_table_snapshot` VARCHAR(64) NULL,
    `legacy_id_snapshot` INT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY `idx_legacy_ami_archive_issues_run` (`run_id`, `severity`),
    CONSTRAINT `fk_legacy_ami_archive_issues_run` FOREIGN KEY (`run_id`) REFERENCES `legacy_ami_archive_runs` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT `fk_legacy_ami_archive_issues_task` FOREIGN KEY (`archive_task_id`) REFERENCES `legacy_ami_archive_tasks` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT `fk_legacy_ami_archive_issues_answer` FOREIGN KEY (`archive_answer_id`) REFERENCES `legacy_ami_archive_answers` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `legacy_ami_archive_user_units` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `run_id` INT NOT NULL,
    `archive_task_id` INT NOT NULL,
    `legacy_user_id` INT NULL,
    `role_snapshot` ENUM('auditor','auditee') NOT NULL,
    `user_name_snapshot` VARCHAR(200) NULL,
    `user_email_snapshot` VARCHAR(200) NULL,
    `unit_name_snapshot` VARCHAR(200) NULL,
    `unit_type_snapshot` VARCHAR(64) NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY `idx_legacy_ami_archive_user_units_run` (`run_id`, `role_snapshot`),
    CONSTRAINT `fk_legacy_ami_archive_user_units_run` FOREIGN KEY (`run_id`) REFERENCES `legacy_ami_archive_runs` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT `fk_legacy_ami_archive_user_units_task` FOREIGN KEY (`archive_task_id`) REFERENCES `legacy_ami_archive_tasks` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
