<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Spmi_indicators extends Admin_Lpmpi_Controller
{
    protected $service;
    public function __construct() { parent::__construct(); $this->load->helper(['form', 'url']); $this->load->library('form_validation'); require_once APPPATH . 'services/Spmi_indicators_service.php'; $this->service = new Spmi_indicators_service(); }
    public function index() { $this->render('index', ['title' => 'Indikator SPMI', 'page_title' => 'Indikator SPMI', 'page_subtitle' => 'Beranda / Indikator SPMI', 'active_menu' => 'spmi_indicators', 'standards' => $this->service->standards()]); }
    public function indicator_create($standard_id) { $standard = $this->service->standard($standard_id); if (!$standard) { show_error('Standar tidak ditemukan.', 404, 'Not Found'); return; } if (!$this->service->is_mutable($this->service->standard_version($standard_id))) { $this->readonly_redirect(); return; } $this->render('indicator_form', $this->form_data('Tambah Indikator SPMI', 'lpmpi/spmi-indicators/indicator/store/' . (int) $standard_id, NULL, $standard)); }
    public function indicator_store($standard_id) { $this->require_post(); $this->set_indicator_rules(); if (!$this->form_validation->run()) { $this->indicator_create($standard_id); return; } $this->flash_redirect($this->service->create_indicator($standard_id, $this->input->post(NULL, TRUE)), 'lpmpi/spmi-indicators/indicator/create/' . (int) $standard_id); }
    public function indicator_detail($id) { $indicator = $this->service->indicator($id); if (!$indicator) { show_error('Indikator tidak ditemukan.', 404, 'Not Found'); return; } $version = (object) ['status' => $indicator->version_status]; $this->render('indicator_detail', ['title' => 'Detail Indikator SPMI', 'page_title' => 'Detail Indikator SPMI', 'page_subtitle' => 'Beranda / Indikator SPMI / Detail', 'active_menu' => 'spmi_indicators', 'indicator' => $indicator, 'targets' => $this->service->targets($id), 'mutable' => $this->service->is_mutable($version)]); }
    public function indicator_edit($id) { $indicator = $this->service->indicator($id); if (!$indicator) { show_error('Indikator tidak ditemukan.', 404, 'Not Found'); return; } if (!in_array($indicator->version_status, ['draft', 'review'], TRUE)) { $this->readonly_redirect(); return; } $this->render('indicator_form', $this->form_data('Edit Indikator SPMI', 'lpmpi/spmi-indicators/indicator/update/' . (int) $id, $indicator, $this->service->standard($indicator->standard_id))); }
    public function indicator_update($id) { $this->require_post(); $this->set_indicator_rules(); if (!$this->form_validation->run()) { $this->indicator_edit($id); return; } $this->flash_redirect($this->service->update_indicator($id, $this->input->post(NULL, TRUE)), 'lpmpi/spmi-indicators/indicator/detail/' . (int) $id); }
    public function target_create($indicator_id) { $indicator = $this->service->indicator($indicator_id); if (!$indicator) { show_error('Indikator tidak ditemukan.', 404, 'Not Found'); return; } if (!in_array($indicator->version_status, ['draft', 'review'], TRUE)) { $this->readonly_redirect(); return; } $this->render('target_form', ['title' => 'Tambah Target Tahunan', 'page_title' => 'Target Tahunan', 'page_subtitle' => 'Beranda / Indikator SPMI / Target', 'active_menu' => 'spmi_indicators', 'action' => 'lpmpi/spmi-indicators/target/store/' . (int) $indicator_id, 'target' => NULL, 'indicator' => $indicator]); }
    public function target_store($indicator_id) { $this->require_post(); $this->set_target_rules(); if (!$this->form_validation->run()) { $this->target_create($indicator_id); return; } $this->flash_redirect($this->service->create_target($indicator_id, $this->input->post(NULL, TRUE)), 'lpmpi/spmi-indicators/indicator/detail/' . (int) $indicator_id); }
    public function target_edit($id) { $target = $this->service->target($id); if (!$target) { show_error('Target tidak ditemukan.', 404, 'Not Found'); return; } $indicator = $this->service->indicator($target->indicator_id); if (!$indicator) { show_error('Indikator tidak ditemukan.', 404, 'Not Found'); return; } if (!in_array($indicator->version_status, ['draft', 'review'], TRUE)) { $this->readonly_redirect(); return; } $this->render('target_form', ['title' => 'Edit Target Tahunan', 'page_title' => 'Target Tahunan', 'page_subtitle' => 'Beranda / Indikator SPMI / Target', 'active_menu' => 'spmi_indicators', 'action' => 'lpmpi/spmi-indicators/target/update/' . (int) $id, 'target' => $target, 'indicator' => $indicator]); }
    public function target_update($id) { $this->require_post(); $target = $this->service->target($id); if (!$target) { show_error('Target tidak ditemukan.', 404, 'Not Found'); return; } $this->set_target_rules(); if (!$this->form_validation->run()) { $this->target_edit($id); return; } $this->flash_redirect($this->service->update_target($id, $this->input->post(NULL, TRUE)), 'lpmpi/spmi-indicators/indicator/detail/' . (int) $target->indicator_id); }
    private function render($view, $data) { $this->load->view('lpmpi/spmi_indicators/' . $view, $data); }
    private function form_data($title, $action, $indicator, $standard) { return ['title' => $title, 'page_title' => 'Indikator SPMI', 'page_subtitle' => 'Beranda / Indikator SPMI / Form', 'active_menu' => 'spmi_indicators', 'action' => $action, 'indicator' => $indicator, 'standard' => $standard, 'units' => $this->service->units()]; }
    private function set_indicator_rules() { $this->form_validation->set_rules('indicator_code', 'Kode indikator', 'required|max_length[64]'); $this->form_validation->set_rules('indicator_type', 'Jenis indikator', 'required|in_list[IKU,IKT]'); $this->form_validation->set_rules('title', 'Judul', 'required|max_length[200]'); $this->form_validation->set_rules('scope_organization_unit_id', 'Unit lingkup', 'required|integer'); $this->form_validation->set_rules('responsible_organization_unit_id', 'Unit penanggung jawab', 'required|integer'); $this->form_validation->set_rules('responsible_pic_name', 'PIC', 'max_length[200]'); $this->form_validation->set_rules('evidence_requirement', 'Kebutuhan bukti', 'required'); }
    private function set_target_rules() { $this->form_validation->set_rules('target_year', 'Tahun target', 'required|integer|greater_than_equal_to[2000]|less_than_equal_to[2100]'); $this->form_validation->set_rules('target_value', 'Target', 'required'); }
    private function require_post() { if ($this->input->method(TRUE) !== 'POST') { show_error('Method tidak diizinkan.', 405, 'Method Not Allowed'); exit; } }
    private function flash_redirect($result, $uri) { $this->session->set_flashdata($result['success'] ? 'success' : 'error', $result['message']); redirect($uri); }
    private function readonly_redirect() { $this->session->set_flashdata('error', 'Versi approved, active, dan retired bersifat hanya-baca.'); redirect('lpmpi/spmi-indicators'); }
}
