<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Spmi_audits extends Admin_Lpmpi_Controller
{
    protected $service;
    public function __construct() { parent::__construct(); $this->load->helper(['form', 'url']); $this->load->library('form_validation'); require_once APPPATH . 'services/Spmi_audits_service.php'; $this->service = new Spmi_audits_service(); }
    public function index() { $this->render('index', ['title' => 'Siklus & Penugasan SPMI', 'page_title' => 'Siklus & Penugasan SPMI', 'page_subtitle' => 'Beranda / Siklus & Penugasan SPMI', 'active_menu' => 'spmi_audits', 'cycles' => $this->service->cycles()]); }
    public function cycle_create() { $this->render('cycle_form', $this->cycle_form_data('Tambah Siklus SPMI', 'lpmpi/spmi-audits/cycle/store', NULL)); }
    public function cycle_store() { $this->require_post(); $this->cycle_rules(); if (!$this->form_validation->run()) { $this->cycle_create(); return; } $this->flash_redirect($this->service->create_cycle($this->input->post(NULL, TRUE), $this->session->userdata('user_id')), 'lpmpi/spmi-audits'); }
    public function cycle_edit($id) { $cycle = $this->service->cycle($id); if (!$cycle) { show_error('Siklus tidak ditemukan.', 404, 'Not Found'); return; } if ($cycle->state !== 'draft') { $this->frozen_redirect(); return; } $this->render('cycle_form', $this->cycle_form_data('Edit Siklus SPMI', 'lpmpi/spmi-audits/cycle/update/' . (int) $id, $cycle)); }
    public function cycle_update($id) { $this->require_post(); $this->cycle_rules(); if (!$this->form_validation->run()) { $this->cycle_edit($id); return; } $this->flash_redirect($this->service->update_cycle($id, $this->input->post(NULL, TRUE)), 'lpmpi/spmi-audits/cycle/detail/' . (int) $id); }
    public function cycle_detail($id) { $cycle = $this->service->cycle($id); if (!$cycle) { show_error('Siklus tidak ditemukan.', 404, 'Not Found'); return; } $this->render('cycle_detail', ['title' => 'Detail Siklus SPMI', 'page_title' => 'Detail Siklus SPMI', 'page_subtitle' => 'Beranda / Siklus & Penugasan SPMI / Detail', 'active_menu' => 'spmi_audits', 'cycle' => $cycle, 'assignments' => $this->service->assignments($id)]); }
    public function cycle_transition($id) { $this->require_post(); $this->flash_redirect($this->service->transition($id, $this->input->post('state', TRUE)), 'lpmpi/spmi-audits/cycle/detail/' . (int) $id); }
    public function assignment_create($cycle_id) { $cycle = $this->service->cycle($cycle_id); if (!$cycle) { show_error('Siklus tidak ditemukan.', 404, 'Not Found'); return; } if ($cycle->state !== 'draft') { $this->frozen_redirect(); return; } $this->render('assignment_form', ['title' => 'Tambah Penugasan SPMI', 'page_title' => 'Tambah Penugasan SPMI', 'page_subtitle' => 'Beranda / Siklus & Penugasan SPMI / Penugasan', 'active_menu' => 'spmi_audits', 'cycle' => $cycle, 'packages' => $this->service->packages(), 'auditors' => $this->service->auditors(), 'auditees' => $this->service->auditees()]); }
    public function assignment_store($cycle_id) { $this->require_post(); $this->form_validation->set_rules('source_package_id', 'Paket instrumen', 'required|integer'); $this->form_validation->set_rules('auditor_id', 'Auditor', 'required|integer'); $this->form_validation->set_rules('auditee_id', 'Auditee', 'required|integer'); if (!$this->form_validation->run()) { $this->assignment_create($cycle_id); return; } $this->flash_redirect($this->service->create_assignment($cycle_id, $this->input->post(NULL, TRUE), $this->session->userdata('user_id')), 'lpmpi/spmi-audits/cycle/detail/' . (int) $cycle_id); }
    public function assignment_detail($id) { $assignment = $this->service->assignment($id); if (!$assignment) { show_error('Penugasan tidak ditemukan.', 404, 'Not Found'); return; } $items = $this->service->items($id); $rubrics_by_item = []; foreach ($items as $item) $rubrics_by_item[$item->id] = $this->service->rubrics($item->id); $this->render('assignment_detail', ['title' => 'Detail Penugasan SPMI', 'page_title' => 'Detail Penugasan SPMI', 'page_subtitle' => 'Beranda / Siklus & Penugasan SPMI / Snapshot', 'active_menu' => 'spmi_audits', 'assignment' => $assignment, 'items' => $items, 'rubrics_by_item' => $rubrics_by_item]); }
    public function assignment_delete($id) { $this->require_post(); $assignment = $this->service->assignment($id); $this->flash_redirect($this->service->delete_assignment($id), $assignment ? 'lpmpi/spmi-audits/cycle/detail/' . (int) $assignment->cycle_id : 'lpmpi/spmi-audits'); }
    private function render($view, $data) { $this->load->view('lpmpi/spmi_audits/' . $view, $data); }
    private function cycle_form_data($title, $action, $cycle) { return ['title' => $title, 'page_title' => $title, 'page_subtitle' => 'Beranda / Siklus & Penugasan SPMI / Form', 'active_menu' => 'spmi_audits', 'action' => $action, 'cycle' => $cycle]; }
    private function cycle_rules() { $this->form_validation->set_rules('cycle_code', 'Kode siklus', 'required|max_length[64]'); $this->form_validation->set_rules('title', 'Judul', 'required|max_length[200]'); $this->form_validation->set_rules('start_date', 'Tanggal mulai', 'required'); $this->form_validation->set_rules('end_date', 'Tanggal selesai', 'required'); }
    private function require_post() { if ($this->input->method(TRUE) !== 'POST') { show_error('Method tidak diizinkan.', 405, 'Method Not Allowed'); exit; } }
    private function flash_redirect($result, $uri) { $this->session->set_flashdata($result['success'] ? 'success' : 'error', $result['message']); redirect($uri); }
    private function frozen_redirect() { $this->session->set_flashdata('error', 'Siklus configured atau closed bersifat hanya-baca.'); redirect('lpmpi/spmi-audits'); }
}
