<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Spmi_master extends Admin_Lpmpi_Controller
{
    protected $service;
    public function __construct() { parent::__construct(); $this->load->helper(['form', 'url']); require_once APPPATH . 'services/Spmi_master_service.php'; $this->service = new Spmi_master_service(); }
    public function index() { $this->render('index', ['title' => 'Import/Export Master SPMI', 'page_title' => 'Import/Export Master SPMI', 'page_subtitle' => 'Beranda / Master SPMI', 'active_menu' => 'spmi_master', 'versions' => $this->service->versions(), 'error' => $this->session->flashdata('error'), 'success' => $this->session->flashdata('success')]); }
    public function template($id) { $this->download($id, TRUE); }
    public function export($id) { $this->download($id, FALSE); }
    public function preview($id) { $this->require_post(); $this->purge_expired_artifacts(); $version = $this->service->version($id); if (!$this->service->mutable($version)) return $this->fail_redirect('Versi tidak tersedia untuk import.'); if (!isset($_FILES['master_file']) || !is_uploaded_file($_FILES['master_file']['tmp_name'])) return $this->fail_redirect('File upload tidak valid.'); $file = $_FILES['master_file']; if ((int) $file['error'] !== UPLOAD_ERR_OK) return $this->fail_redirect('Upload gagal: kode error ' . (int) $file['error'] . '.'); if (strtolower(pathinfo($file['name'], PATHINFO_EXTENSION)) !== 'xlsx' || (int) $file['size'] > 2 * 1024 * 1024) return $this->fail_redirect('File wajib .xlsx dan maksimal 2 MiB.'); $mime = (new finfo(FILEINFO_MIME_TYPE))->file($file['tmp_name']); if (!in_array($mime, ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/zip'], TRUE)) return $this->fail_redirect('MIME file tidak didukung.'); $path = $this->private_tmp() . 'spmi_master_upload_' . bin2hex(random_bytes(12)) . '.xlsx'; if (!move_uploaded_file($file['tmp_name'], $path)) return $this->fail_redirect('File upload tidak dapat disimpan.'); try { $result = $this->service->parse($path); } catch (Throwable $e) { $result = ['valid' => [], 'errors' => [['row' => 0, 'message' => $e->getMessage()]], 'total' => 0]; } finally { if (is_file($path)) unlink($path); } if (empty($result['valid'])) return $this->fail_redirect('Preview ditolak: tidak ada baris valid.'); $this->clear_preview(); $token = bin2hex(random_bytes(16)); $basename = 'spmi_master_preview_' . bin2hex(random_bytes(12)) . '.json'; file_put_contents($this->private_tmp() . $basename, json_encode($result, JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR), LOCK_EX); $metadata = ['user_id' => $this->_user_id(), 'version_id' => (int) $id, 'basename' => $basename, 'sha256' => hash_file('sha256', $this->private_tmp() . $basename), 'created_at' => time(), 'token' => $token]; $this->session->set_userdata('spmi_master_preview', $metadata); $this->render('import_preview', ['title' => 'Preview Import Master SPMI', 'page_title' => 'Preview Import Master SPMI', 'page_subtitle' => 'Beranda / Master SPMI / Preview', 'active_menu' => 'spmi_master', 'version' => $version, 'token' => $token, 'valid' => $result['valid'], 'errors' => $result['errors'], 'total' => $result['total']]); }
    public function confirm($id) { $this->require_post(); $this->purge_expired_artifacts(); $meta = $this->session->userdata('spmi_master_preview'); $path = is_array($meta) && isset($meta['basename']) ? $this->private_tmp() . basename($meta['basename']) : ''; if (!is_array($meta) || !hash_equals((string) $meta['token'], (string) $this->input->post('token', TRUE)) || (int) $meta['user_id'] !== $this->_user_id() || (int) $meta['version_id'] !== (int) $id || time() - (int) $meta['created_at'] > 1800 || !is_file($path) || !hash_equals($meta['sha256'], hash_file('sha256', $path))) return $this->fail_redirect('Preview tidak valid atau sudah kedaluwarsa.'); $claim = $this->private_tmp() . 'spmi_master_claim_' . bin2hex(random_bytes(12)) . '.json'; if (!rename($path, $claim)) return $this->fail_redirect('Preview sedang tidak tersedia.'); $this->session->unset_userdata('spmi_master_preview'); try { $payload = json_decode(file_get_contents($claim), TRUE, 512, JSON_THROW_ON_ERROR); $result = $this->service->confirm($id, isset($payload['valid']) ? $payload['valid'] : []); } catch (Throwable $e) { log_message('error', 'SPMI master confirm failed: ' . $e->getMessage()); $result = ['success' => FALSE, 'message' => 'Import Master SPMI gagal diproses. Silakan unggah ulang preview.']; } finally { if (is_file($claim)) unlink($claim); } $this->session->set_flashdata($result['success'] ? 'success' : 'error', $result['message']); redirect('lpmpi/spmi-master'); }
    public function cancel($id) { $this->require_post(); $this->purge_expired_artifacts(); $this->clear_preview(); redirect('lpmpi/spmi-master'); }
    private function download($id, $template) { $version = $this->service->version($id); if (!$version) show_error('Versi tidak ditemukan.', 404, 'Not Found'); if ($template && !$this->service->mutable($version)) show_error('Template hanya tersedia untuk versi draft/review.', 403, 'Forbidden'); $this->load_library(); $sheet = (new PhpOffice\PhpSpreadsheet\Spreadsheet())->getActiveSheet(); $sheet->setTitle('SPMI Master'); foreach (Spmi_master_service::HEADERS as $i => $header) $this->text($sheet, $i + 1, 1, $header); $rows = $template ? [] : $this->service->export_rows($id); $line = 2; foreach ($rows as $row) { foreach (['standard_code', 'standard_order', 'standard_title', 'standard_description', 'indicator_code', 'indicator_type', 'indicator_title', 'scope_unit_code', 'responsible_unit_code', 'responsible_pic_name', 'evidence_requirement', 'target_year', 'target_value'] as $i => $key) $this->text($sheet, $i + 1, $line, $row->{$key} === NULL ? '' : $row->{$key}); $line++; } while (ob_get_level() > 0) @ob_end_clean(); header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'); header('Content-Disposition: attachment; filename="spmi_master_' . (int) $id . '.xlsx"'); (new PhpOffice\PhpSpreadsheet\Writer\Xlsx($sheet->getParent()))->save('php://output'); exit; }
    private function text($sheet, $column, $row, $value) { $value = (string) $value; if ($value !== '' && in_array($value[0], ['=', '+', '-', '@'], TRUE)) $value = "'" . $value; $sheet->setCellValueExplicitByColumnAndRow($column, $row, $value, PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_STRING); }
    private function load_library() { require_once FCPATH . 'vendor/autoload.php'; }
    private function render($view, $data) { $this->load->view('lpmpi/spmi_master/' . $view, $data); }
    private function private_tmp() { $dir = private_storage_dir('tmp'); if (!is_dir($dir)) mkdir($dir, 0700, TRUE); return $dir; }
    private function clear_preview() { $meta = $this->session->userdata('spmi_master_preview'); if (is_array($meta) && isset($meta['basename'])) { $path = $this->private_tmp() . basename($meta['basename']); if (is_file($path)) unlink($path); } $this->session->unset_userdata('spmi_master_preview'); }
    private function purge_expired_artifacts() { $dir = private_storage_dir('tmp'); $cutoff = time() - 1800; $current = $this->session->userdata('spmi_master_preview'); $current_basename = is_array($current) && isset($current['basename']) ? basename($current['basename']) : ''; foreach (['spmi_master_preview_*.json', 'spmi_master_claim_*.json'] as $pattern) foreach (glob($dir . $pattern, GLOB_NOSORT) ?: [] as $path) { $basename = basename($path); if ($basename === $current_basename || !preg_match('/^spmi_master_(?:preview|claim)_[a-f0-9]+\.json$/', $basename) || !is_file($path) || filemtime($path) >= $cutoff) continue; unlink($dir . $basename); } }
    private function fail_redirect($message) { $this->session->set_flashdata('error', $message); redirect('lpmpi/spmi-master'); }
    private function require_post() { if ($this->input->method(TRUE) !== 'POST') { show_error('Method tidak diizinkan.', 405, 'Method Not Allowed'); exit; } }
}
