<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Spmi_master extends Admin_Lpmpi_Controller
{
    protected $service;
    public function __construct() { parent::__construct(); $this->load->helper(['form', 'url']); require_once APPPATH . 'services/Spmi_master_service.php'; $this->service = new Spmi_master_service(); }
    public function index() { $this->session->keep_flashdata(['success', 'error']); redirect('lpmpi/spmi-standards'); }
    public function template($id) { $this->download($id, TRUE); }
    public function export($id) { $this->download($id, FALSE); }
    public function preview($id) { $this->require_post(); $this->purge_expired_artifacts(); $version = $this->service->version($id); if (!$this->service->mutable($version)) return $this->fail_redirect('Versi tidak tersedia untuk import.'); if (!isset($_FILES['master_file']) || !is_uploaded_file($_FILES['master_file']['tmp_name'])) return $this->fail_redirect('File upload tidak valid.'); $file = $_FILES['master_file']; $limit_bytes = $this->upload_limit_bytes('spreadsheet_imports'); $limit_mib = $this->limit_mib($limit_bytes); if ((int) $file['error'] !== UPLOAD_ERR_OK) return $this->fail_redirect('Upload gagal: kode error ' . (int) $file['error'] . '.'); if (strtolower(pathinfo($file['name'], PATHINFO_EXTENSION)) !== 'xlsx' || (int) $file['size'] > $limit_bytes) return $this->fail_redirect('File wajib .xlsx dan maksimal ' . $limit_mib . ' MiB.'); $mime = (new finfo(FILEINFO_MIME_TYPE))->file($file['tmp_name']); if (!in_array($mime, ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/zip'], TRUE)) return $this->fail_redirect('MIME file tidak didukung.'); $path = $this->private_tmp() . 'spmi_master_upload_' . bin2hex(random_bytes(12)) . '.xlsx'; if (!move_uploaded_file($file['tmp_name'], $path)) return $this->fail_redirect('File upload tidak dapat disimpan.'); try { $result = $this->service->parse($path); } catch (Throwable $e) { log_message('error', 'SPMI master preview failed: ' . $e->getMessage()); $result = ['valid' => [], 'errors' => [['row' => 0, 'message' => 'Workbook tidak dapat diproses.']], 'total' => 0]; } finally { if (is_file($path)) unlink($path); } if (empty($result['valid'])) return $this->render('import_preview', ['title' => 'Preview Import Master SPMI', 'page_title' => 'Preview Import Master SPMI', 'page_subtitle' => 'Beranda / Master SPMI / Preview', 'active_menu' => 'spmi_master', 'version' => $version, 'token' => '', 'valid' => $result['valid'], 'errors' => $result['errors'], 'total' => $result['total']]); $this->clear_preview(); $token = bin2hex(random_bytes(16)); $basename = 'spmi_master_preview_' . bin2hex(random_bytes(12)) . '.json'; file_put_contents($this->private_tmp() . $basename, json_encode($result, JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR), LOCK_EX); $metadata = ['user_id' => $this->_user_id(), 'version_id' => (int) $id, 'basename' => $basename, 'sha256' => hash_file('sha256', $this->private_tmp() . $basename), 'created_at' => time(), 'token' => $token]; $this->session->set_userdata('spmi_master_preview', $metadata); $this->render('import_preview', ['title' => 'Preview Import Master SPMI', 'page_title' => 'Preview Import Master SPMI', 'page_subtitle' => 'Beranda / Master SPMI / Preview', 'active_menu' => 'spmi_master', 'version' => $version, 'token' => $token, 'valid' => $result['valid'], 'errors' => $result['errors'], 'total' => $result['total']]); }
    public function confirm($id) { $this->require_post(); $this->purge_expired_artifacts(); $meta = $this->session->userdata('spmi_master_preview'); $path = is_array($meta) && isset($meta['basename']) ? $this->private_tmp() . basename($meta['basename']) : ''; if (!is_array($meta) || !hash_equals((string) $meta['token'], (string) $this->input->post('token', TRUE)) || (int) $meta['user_id'] !== $this->_user_id() || (int) $meta['version_id'] !== (int) $id || time() - (int) $meta['created_at'] > 1800 || !is_file($path) || !hash_equals($meta['sha256'], hash_file('sha256', $path))) return $this->fail_redirect('Preview tidak valid atau sudah kedaluwarsa.'); $claim = $this->private_tmp() . 'spmi_master_claim_' . bin2hex(random_bytes(12)) . '.json'; if (!rename($path, $claim)) return $this->fail_redirect('Preview sedang tidak tersedia.'); $this->session->unset_userdata('spmi_master_preview'); try { $payload = json_decode(file_get_contents($claim), TRUE, 512, JSON_THROW_ON_ERROR); $result = $this->service->confirm($id, isset($payload['valid']) ? $payload['valid'] : []); } catch (Throwable $e) { log_message('error', 'SPMI master confirm failed: ' . $e->getMessage()); $result = ['success' => FALSE, 'message' => 'Import Master SPMI gagal diproses. Silakan unggah ulang preview.']; } finally { if (is_file($claim)) unlink($claim); } $this->session->set_flashdata($result['success'] ? 'success' : 'error', $result['message']); redirect('lpmpi/spmi-standards'); }
    public function cancel($id) { $this->require_post(); $this->purge_expired_artifacts(); $this->clear_preview(); redirect('lpmpi/spmi-standards'); }
    private function download($id, $template) { $version = $this->service->version($id); if (!$version) show_error('Versi tidak ditemukan.', 404, 'Not Found'); if ($template && !$this->service->mutable($version)) show_error('Template hanya tersedia untuk versi draft/review.', 403, 'Forbidden'); $this->load_library(); $spreadsheet = new PhpOffice\PhpSpreadsheet\Spreadsheet(); $sheet = $spreadsheet->getActiveSheet(); $sheet->setTitle('SPMI Master'); foreach (Spmi_master_service::HEADERS as $i => $header) $this->text($sheet, $i + 1, 1, $header); $rows = $template ? [] : $this->service->export_rows($id); $line = 2; foreach ($rows as $row) { foreach (['standard_code', 'standard_order', 'standard_title', 'standard_description', 'indicator_code', 'indicator_type', 'indicator_title', 'scope_unit_code', 'responsible_unit_code', 'responsible_pic_name', 'evidence_requirement', 'target_year', 'target_value', 'evidence_policy'] as $i => $key) $this->text($sheet, $i + 1, $line, $row->{$key} === NULL ? '' : $row->{$key}); $line++; }
        $guide = $spreadsheet->createSheet(); $guide->setTitle('Petunjuk'); $guide->mergeCells('A1:D1'); $this->text($guide, 1, 1, 'Petunjuk Pengisian Template Master SPMI');
        foreach (['Pemetaan dokumen: Kriteria atau Profil UPPS menjadi satu Standar.', 'Setiap poin atau elemen dalam Kriteria menjadi satu Indikator.', 'Nama singkat poin menjadi Indicator Title.', 'Narasi atau deskripsi panjang menjadi Evidence Requirement.', 'Kolom Nilai, Sebutan, Bobot, Nilai Tertimbang, Capaian Prediksi, Akar Penyebab, Rekomendasi, dan RTL adalah hasil audit; tidak diimport atau dipetakan.'] as $row => $note) { $guide->mergeCells('A' . ($row + 3) . ':D' . ($row + 3)); $this->text($guide, 1, $row + 3, $note); }
        foreach (['Kolom', 'Wajib?', 'Isi dengan', 'Aturan'] as $column => $header) $this->text($guide, $column + 1, 9, $header);
        $guidance = [
            ['Standard Code', 'Wajib', 'Kode unik standar, mis. STD-01', 'A-Z0-9._- saja; sama untuk semua indikator dalam standar yang sama'],
            ['Standard Order', 'Wajib', 'Urutan tampil standar', 'Bilangan bulat positif; konsisten untuk Standard Code yang sama'],
            ['Standard Title', 'Wajib', 'Nama standar', 'Konsisten untuk Standard Code yang sama'],
            ['Standard Description', 'Opsional', 'Deskripsi tambahan standar', 'Boleh kosong; konsisten untuk Standard Code yang sama'],
            ['Indicator Code', 'Wajib', 'Kode unik indikator, mis. IND-001', 'A-Z0-9._- saja; unik dalam satu Standard Code'],
            ['Indicator Type', 'Wajib', 'IKU atau IKT', 'Hanya dua nilai ini'],
            ['Indicator Title', 'Wajib', 'Nama singkat indikator', 'Maks. 200 karakter'],
            ['Scope Unit Code', 'Wajib', 'Kode unit organisasi lingkup', 'Harus sudah aktif di menu Unit Organisasi'],
            ['Responsible Unit Code', 'Wajib', 'Kode unit organisasi penanggung jawab', 'Harus sudah aktif di menu Unit Organisasi'],
            ['Responsible PIC', 'Opsional', 'Nama PIC', '-'],
            ['Evidence Requirement', 'Wajib', 'Narasi lengkap bukti atau kriteria', 'Teks bebas, tanpa batas panjang'],
            ['Target Year', 'Opsional', 'Tahun target', '2000-2100; wajib bersamaan dengan Target Value'],
            ['Target Value', 'Opsional', 'Nilai target', 'Wajib bersamaan dengan Target Year'],
            ['Evidence Policy', 'Wajib', 'none, file, url, either, atau both', 'Tidak case-sensitive saat diimport; disimpan lowercase'],
        ];
        foreach ($guidance as $row => $values) foreach ($values as $column => $value) $this->text($guide, $column + 1, $row + 10, $value);
        $this->text($guide, 1, 24, 'Contoh - jangan disalin ke sheet SPMI Master apa adanya, sesuaikan datanya');
        foreach (Spmi_master_service::HEADERS as $column => $header) $this->text($guide, $column + 1, 25, $header);
        foreach (['STD-01', '1', 'Kriteria Visi Keilmuan', '', 'IND-001', 'IKU', 'Kesesuaian visi keilmuan', 'FTS', 'FTS', 'Dekan FTS', 'Dokumen visi keilmuan yang disahkan.', '2026', '90', 'file'] as $column => $value) $this->text($guide, $column + 1, 26, $value);
        $guide->getStyle('A1:D1')->getFont()->setBold(TRUE); $guide->getStyle('A9:D9')->getFont()->setBold(TRUE); $guide->getStyle('A24')->getFont()->setBold(TRUE); $guide->getStyle('A25:N25')->getFont()->setBold(TRUE); $guide->getStyle('A3:D26')->getAlignment()->setWrapText(TRUE); foreach (['A' => 24, 'B' => 14, 'C' => 38, 'D' => 56] as $column => $width) $guide->getColumnDimension($column)->setWidth($width); $spreadsheet->setActiveSheetIndex(0);
        while (ob_get_level() > 0) @ob_end_clean(); header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'); header('Content-Disposition: attachment; filename="spmi_master_' . (int) $id . '.xlsx"'); (new PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet))->save('php://output'); exit; }
    private function text($sheet, $column, $row, $value) { $value = (string) $value; if ($value !== '' && in_array($value[0], ['=', '+', '-', '@'], TRUE)) $value = "'" . $value; $sheet->setCellValueExplicitByColumnAndRow($column, $row, $value, PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_STRING); }
    private function load_library() { require_once FCPATH . 'vendor/autoload.php'; }
    private function render($view, $data) { $data['upload_limit_mib'] = $this->limit_mib($this->upload_limit_bytes('spreadsheet_imports')); $this->load->view('lpmpi/spmi_master/' . $view, $data); }
    private function upload_limit_bytes($category) { require_once APPPATH . 'services/Upload_size_settings_service.php'; return (int) Upload_size_settings_service::limit_bytes($category); }
    private function limit_mib($bytes) { return (int) ($bytes / 1024 / 1024); }
    private function private_tmp() { $dir = private_storage_dir('tmp'); if (!is_dir($dir)) mkdir($dir, 0700, TRUE); return $dir; }
    private function clear_preview() { $meta = $this->session->userdata('spmi_master_preview'); if (is_array($meta) && isset($meta['basename'])) { $path = $this->private_tmp() . basename($meta['basename']); if (is_file($path)) unlink($path); } $this->session->unset_userdata('spmi_master_preview'); }
    private function purge_expired_artifacts() { $dir = private_storage_dir('tmp'); $cutoff = time() - 1800; $current = $this->session->userdata('spmi_master_preview'); $current_basename = is_array($current) && isset($current['basename']) ? basename($current['basename']) : ''; foreach (['spmi_master_preview_*.json', 'spmi_master_claim_*.json'] as $pattern) foreach (glob($dir . $pattern, GLOB_NOSORT) ?: [] as $path) { $basename = basename($path); if ($basename === $current_basename || !preg_match('/^spmi_master_(?:preview|claim)_[a-f0-9]+\.json$/', $basename) || !is_file($path) || filemtime($path) >= $cutoff) continue; unlink($dir . $basename); } }
    private function fail_redirect($message) { $this->session->set_flashdata('error', $message); redirect('lpmpi/spmi-standards'); }
    private function require_post() { if ($this->input->method(TRUE) !== 'POST') { show_error('Method tidak diizinkan.', 405, 'Method Not Allowed'); exit; } }
}
