<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Spmi_instruments extends Admin_Lpmpi_Controller
{
    protected $service;
    public function __construct() { parent::__construct(); $this->load->helper(['form', 'url']); $this->load->library('form_validation'); require_once APPPATH . 'services/Spmi_instruments_service.php'; $this->service = new Spmi_instruments_service(); }
    public function index() { $this->render('index', ['title' => 'Instrumen Audit SPMI', 'page_title' => 'Instrumen Audit SPMI', 'page_subtitle' => 'Beranda / Instrumen Audit SPMI', 'active_menu' => 'spmi_instruments', 'standards' => $this->service->standards(), 'packages' => $this->service->all_packages()]); }
    public function package_create($standard_id) { $standard = $this->service->standard($standard_id); if (!$standard) { show_error('Standar tidak ditemukan.', 404, 'Not Found'); return; } if (!$this->service->is_mutable($this->service->standard_version($standard_id))) { $this->readonly_redirect(); return; } $this->render('package_form', $this->form_data('Tambah Paket Instrumen', 'lpmpi/spmi-instruments/package/store/' . (int) $standard_id, NULL, $standard)); }
    public function package_store($standard_id) { $this->require_post(); $this->set_package_rules(); if (!$this->form_validation->run()) { $this->package_create($standard_id); return; } $this->flash_redirect($this->service->create_package($standard_id, $this->input->post(NULL, TRUE)), 'lpmpi/spmi-instruments'); }
    public function package_detail($id) { $package = $this->service->package($id); if (!$package) { show_error('Paket tidak ditemukan.', 404, 'Not Found'); return; } $this->render('package_detail', ['title' => 'Detail Paket Instrumen', 'page_title' => 'Paket Instrumen SPMI', 'page_subtitle' => 'Beranda / Instrumen Audit SPMI / Detail', 'active_menu' => 'spmi_instruments', 'package' => $package, 'questions' => $this->service->questions($id), 'mutable' => $this->service->is_mutable((object) ['status' => $package->version_status])]); }
    public function package_edit($id) { $package = $this->service->package($id); if (!$package) { show_error('Paket tidak ditemukan.', 404, 'Not Found'); return; } if (!$this->service->is_mutable((object) ['status' => $package->version_status])) { $this->readonly_redirect(); return; } $this->render('package_form', $this->form_data('Edit Paket Instrumen', 'lpmpi/spmi-instruments/package/update/' . (int) $id, $package, $this->service->standard($package->standard_id))); }
    public function package_update($id) { $this->require_post(); $this->set_package_rules(); if (!$this->form_validation->run()) { $this->package_edit($id); return; } $this->flash_redirect($this->service->update_package($id, $this->input->post(NULL, TRUE)), 'lpmpi/spmi-instruments/package/detail/' . (int) $id); }
    public function package_delete($id) { $this->require_post(); $package = $this->service->package($id); $this->flash_redirect($this->service->delete_package($id), $package ? 'lpmpi/spmi-instruments' : 'lpmpi/spmi-instruments'); }
    public function question_create($package_id) { $package = $this->service->package($package_id); if (!$package) { show_error('Paket tidak ditemukan.', 404, 'Not Found'); return; } if (!$this->service->is_mutable((object) ['status' => $package->version_status])) { $this->readonly_redirect(); return; } $this->render('question_form', ['title' => 'Tambah Pertanyaan Instrumen', 'page_title' => 'Pertanyaan Instrumen', 'page_subtitle' => 'Beranda / Instrumen Audit SPMI / Pertanyaan', 'active_menu' => 'spmi_instruments', 'action' => 'lpmpi/spmi-instruments/question/store/' . (int) $package_id, 'question' => NULL, 'package' => $package, 'indicators' => $this->service->indicators($package->standard_id)]); }
    public function question_store($package_id) { $this->require_post(); $this->set_question_rules(); if (!$this->form_validation->run()) { $this->question_create($package_id); return; } $this->flash_redirect($this->service->create_question($package_id, $this->input->post(NULL, TRUE)), 'lpmpi/spmi-instruments/package/detail/' . (int) $package_id); }
    public function question_detail($id) { $question = $this->service->question($id); if (!$question) { show_error('Pertanyaan tidak ditemukan.', 404, 'Not Found'); return; } $this->render('question_detail', ['title' => 'Detail Pertanyaan Instrumen', 'page_title' => 'Pertanyaan Instrumen', 'page_subtitle' => 'Beranda / Instrumen Audit SPMI / Pertanyaan', 'active_menu' => 'spmi_instruments', 'question' => $question, 'rubrics' => $this->service->rubrics($id), 'mutable' => $this->service->is_mutable((object) ['status' => $question->version_status])]); }
    public function question_edit($id) { $question = $this->service->question($id); if (!$question) { show_error('Pertanyaan tidak ditemukan.', 404, 'Not Found'); return; } if (!$this->service->is_mutable((object) ['status' => $question->version_status])) { $this->readonly_redirect(); return; } $package = $this->service->package($question->package_id); $this->render('question_form', ['title' => 'Edit Pertanyaan Instrumen', 'page_title' => 'Pertanyaan Instrumen', 'page_subtitle' => 'Beranda / Instrumen Audit SPMI / Pertanyaan', 'active_menu' => 'spmi_instruments', 'action' => 'lpmpi/spmi-instruments/question/update/' . (int) $id, 'question' => $question, 'package' => $package, 'indicators' => $this->service->indicators($package->standard_id)]); }
    public function question_update($id) { $this->require_post(); $this->set_question_rules(); $question = $this->service->question($id); if (!$this->form_validation->run()) { $this->question_edit($id); return; } $this->flash_redirect($this->service->update_question($id, $this->input->post(NULL, TRUE)), 'lpmpi/spmi-instruments/question/detail/' . (int) $id); }
    public function question_delete($id) { $this->require_post(); $question = $this->service->question($id); $this->flash_redirect($this->service->delete_question($id), $question ? 'lpmpi/spmi-instruments/package/detail/' . (int) $question->package_id : 'lpmpi/spmi-instruments'); }
    public function rubric_create($question_id) { $question = $this->service->question($question_id); if (!$question) { show_error('Pertanyaan tidak ditemukan.', 404, 'Not Found'); return; } if (!$this->service->is_mutable((object) ['status' => $question->version_status])) { $this->readonly_redirect(); return; } $this->render('rubric_form', ['title' => 'Tambah Rubrik', 'page_title' => 'Rubrik Pertanyaan', 'page_subtitle' => 'Beranda / Instrumen Audit SPMI / Rubrik', 'active_menu' => 'spmi_instruments', 'action' => 'lpmpi/spmi-instruments/rubric/store/' . (int) $question_id, 'rubric' => NULL, 'question' => $question]); }
    public function rubric_store($question_id) { $this->require_post(); $this->set_rubric_rules(); if (!$this->form_validation->run()) { $this->rubric_create($question_id); return; } $this->flash_redirect($this->service->create_rubric($question_id, $this->input->post(NULL, TRUE)), 'lpmpi/spmi-instruments/question/detail/' . (int) $question_id); }
    public function rubric_edit($id) { $rubric = $this->service->rubric($id); if (!$rubric) { show_error('Rubrik tidak ditemukan.', 404, 'Not Found'); return; } $question = $this->service->question($rubric->question_id); if (!$question || !$this->service->is_mutable((object) ['status' => $question->version_status])) { $this->readonly_redirect(); return; } $this->render('rubric_form', ['title' => 'Edit Rubrik', 'page_title' => 'Rubrik Pertanyaan', 'page_subtitle' => 'Beranda / Instrumen Audit SPMI / Rubrik', 'active_menu' => 'spmi_instruments', 'action' => 'lpmpi/spmi-instruments/rubric/update/' . (int) $id, 'rubric' => $rubric, 'question' => $question]); }
    public function rubric_update($id) { $this->require_post(); $this->set_rubric_rules(); $rubric = $this->service->rubric($id); if (!$this->form_validation->run()) { $this->rubric_edit($id); return; } $this->flash_redirect($this->service->update_rubric($id, $this->input->post(NULL, TRUE)), 'lpmpi/spmi-instruments/question/detail/' . (int) ($rubric ? $rubric->question_id : 0)); }
    public function rubric_delete($id) { $this->require_post(); $rubric = $this->service->rubric($id); $this->flash_redirect($this->service->delete_rubric($id), $rubric ? 'lpmpi/spmi-instruments/question/detail/' . (int) $rubric->question_id : 'lpmpi/spmi-instruments'); }
    private function render($view, $data) { $this->load->view('lpmpi/spmi_instruments/' . $view, $data); }
    private function form_data($title, $action, $package, $standard) { return ['title' => $title, 'page_title' => 'Instrumen Audit SPMI', 'page_subtitle' => 'Beranda / Instrumen Audit SPMI / Form', 'active_menu' => 'spmi_instruments', 'action' => $action, 'package' => $package, 'standard' => $standard]; }
    private function set_package_rules() { $this->form_validation->set_rules('package_code', 'Kode paket', 'required|max_length[64]'); $this->form_validation->set_rules('display_order', 'Urutan', 'required|integer|greater_than[0]'); $this->form_validation->set_rules('title', 'Judul', 'required|max_length[200]'); }
    private function set_question_rules() { $this->form_validation->set_rules('indicator_id', 'Indikator', 'required|integer'); $this->form_validation->set_rules('question_code', 'Kode pertanyaan', 'required|max_length[64]'); $this->form_validation->set_rules('display_order', 'Urutan', 'required|integer|greater_than[0]'); $this->form_validation->set_rules('question_text', 'Pertanyaan', 'required'); $this->form_validation->set_rules('evidence_instruction', 'Instruksi bukti', 'required'); $this->form_validation->set_rules('evidence_policy', 'Kebijakan bukti', 'required|in_list[none,file,url,either,both]'); }
    private function set_rubric_rules() { $this->form_validation->set_rules('score', 'Skor', 'required|integer|greater_than_equal_to[1]|less_than_equal_to[4]'); $this->form_validation->set_rules('descriptor', 'Deskriptor', 'required'); }
    private function require_post() { if ($this->input->method(TRUE) !== 'POST') { show_error('Method tidak diizinkan.', 405, 'Method Not Allowed'); exit; } }
    private function flash_redirect($result, $uri) { $this->session->set_flashdata($result['success'] ? 'success' : 'error', $result['message']); redirect($uri); }
    private function readonly_redirect() { $this->session->set_flashdata('error', 'Versi approved, active, dan retired bersifat hanya-baca.'); redirect('lpmpi/spmi-instruments'); }
}
