<?php defined('BASEPATH') OR exit('No direct script access allowed'); include APPPATH . 'views/layouts/header.php'; include APPPATH . 'views/layouts/sidebar.php'; ?>
<div class="ami-panel"><div class="ami-panel-body">
    <h2 class="ami-section-title">Preview Import Master SPMI</h2><p>Versi: <?php echo html_escape($version->version_code); ?>. Preview sekali pakai, berlaku 30 menit. Confirm memperbarui data secara additive/no-delete.</p>
    <div class="alert alert-info">Total baris: <?php echo html_escape((string) $total); ?>. Diterima: <?php echo html_escape((string) count($valid)); ?>. Ditolak: <?php echo html_escape((string) count($errors)); ?>.</div>
    <?php if ($errors): ?><div class="alert alert-danger"><strong>Error baris</strong><ul><?php foreach ($errors as $error): ?><li>Baris <?php echo html_escape((string) $error['row']); ?>: <?php echo html_escape($error['message']); ?></li><?php endforeach; ?></ul></div><?php endif; ?>
    <?php if ($valid): ?><div class="table-responsive"><table class="table ami-table"><thead><tr><th>Standard</th><th>Indicator</th><th>Unit lingkup</th><th>Unit penanggung jawab</th><th>Target</th></tr></thead><tbody><?php foreach ($valid as $row): ?><tr><td><?php echo html_escape($row['standard_code'] . ' - ' . $row['standard_title']); ?></td><td><?php echo html_escape($row['indicator_code'] . ' - ' . $row['indicator_title']); ?></td><td><?php echo html_escape($row['scope_unit_code']); ?></td><td><?php echo html_escape($row['responsible_unit_code']); ?></td><td><?php echo html_escape((string) ($row['target_year'] === NULL ? '-' : $row['target_year'] . ': ' . $row['target_value'])); ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
    <?php if ($valid): ?><?php echo form_open('lpmpi/spmi-master/confirm/' . (int) $version->id); ?><input type="hidden" name="token" value="<?php echo html_escape($token); ?>"><button class="btn-ami btn-primary" type="submit">Confirm import</button><?php echo form_close(); ?><?php else: ?><p>Confirm tidak tersedia karena zero valid rows.</p><?php endif; ?>
    <?php echo form_open('lpmpi/spmi-master/cancel/' . (int) $version->id); ?><button class="btn-ami btn-outline-ami" type="submit">Batal</button><?php echo form_close(); ?>
</div></div><?php include APPPATH . 'views/layouts/footer.php'; ?>
