<?php defined('BASEPATH') OR exit('No direct script access allowed'); include APPPATH . 'views/layouts/header.php'; include APPPATH . 'views/layouts/sidebar.php'; ?>
<div class="ami-panel"><div class="ami-panel-body">
    <h2 class="ami-section-title">Import/Export Master SPMI</h2>
    <?php if (!empty($error)): ?><div class="alert alert-danger"><?php echo html_escape($error); ?></div><?php endif; ?>
    <?php if (!empty($success)): ?><div class="alert alert-success"><?php echo html_escape($success); ?></div><?php endif; ?>
    <p>Import bersifat additive/no-delete: baris yang tidak ada dalam workbook tetap tersimpan. Template dan import hanya tersedia untuk versi draft/review.</p>
    <?php if (empty($versions)): ?><div class="ami-empty"><div class="ami-empty-title">Belum ada versi</div><div>Buat versi M3 sebelum memakai Master SPMI.</div></div>
    <?php else: ?><div class="table-responsive"><table class="table ami-table"><thead><tr><th>Versi</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php foreach ($versions as $version): ?><tr><td><?php echo html_escape($version->version_code . ' - ' . $version->title); ?></td><td><?php echo html_escape($version->status); ?></td><td><?php if (in_array($version->status, ['draft', 'review'], TRUE)): ?><a class="btn-ami btn-sm btn-outline-ami" href="<?php echo site_url('lpmpi/spmi-master/template/' . (int) $version->id); ?>">Template</a><a class="btn-ami btn-sm btn-outline-ami" href="<?php echo site_url('lpmpi/spmi-master/export/' . (int) $version->id); ?>">Export</a><?php echo form_open_multipart('lpmpi/spmi-master/preview/' . (int) $version->id); ?><input type="file" name="master_file" accept=".xlsx" required><button class="btn-ami btn-sm btn-primary" type="submit">Upload preview</button><?php echo form_close(); ?><?php else: ?><span>Hanya-baca</span> <a class="btn-ami btn-sm btn-outline-ami" href="<?php echo site_url('lpmpi/spmi-master/export/' . (int) $version->id); ?>">Export</a><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
</div></div><?php include APPPATH . 'views/layouts/footer.php'; ?>
