<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Spmi_instruments_service
{
    protected $ci;
    protected $model;
    public function __construct() { $this->ci = &get_instance(); $this->ci->load->model('Spmi_instruments_model'); $this->model = $this->ci->Spmi_instruments_model; }
    public function standards() { return $this->model->get_standards(); }
    public function standard($id) { return $this->model->find_standard($id); }
    public function standard_version($id) { $standard = $this->standard($id); return $standard ? $this->model->find_version($standard->version_id) : NULL; }
    public function indicators($id) { return $this->model->get_indicators($id); }
    public function package($id) { return $this->model->find_package($id); }
    public function packages($standard_id) { return $this->model->get_packages($standard_id); }
    public function all_packages() { return $this->model->get_all_packages(); }
    public function questions($package_id) { return $this->model->get_questions($package_id); }
    public function question($id) { return $this->model->find_question($id); }
    public function rubrics($question_id) { return $this->model->get_rubrics($question_id); }
    public function rubric($id) { return $this->model->find_rubric($id); }
    public function is_mutable($version) { return $version && in_array($version->status, ['draft', 'review'], TRUE); }
    public function create_package($standard_id, $data) { $standard = $this->model->find_standard($standard_id); return $this->package_write('create', 0, $standard, $data); }
    public function update_package($id, $data) { $package = $this->model->find_package_for_update($id); $standard = $package ? $this->model->find_standard($package->standard_id) : NULL; return $this->package_write('update', $id, $standard, $data); }
    public function delete_package($id) { $this->ci->db->trans_begin(); try { $package = $this->model->find_package_for_update($id); $standard = $package ? $this->model->find_standard($package->standard_id) : NULL; $version = $standard ? $this->model->find_version($standard->version_id, TRUE) : NULL; if (!$package || !$this->is_mutable($version)) return $this->rollback('Paket berada pada versi hanya-baca atau tidak ditemukan.'); if ($this->model->count_questions($id) > 0) return $this->rollback('Paket tidak dapat dihapus karena masih memiliki pertanyaan.'); return $this->finish($this->model->delete('spmi_instrument_packages', $id), 'Paket instrumen berhasil dihapus.'); } catch (Throwable $e) { return $this->rollback('Paket instrumen gagal dihapus.'); } }
    public function create_question($package_id, $data) { $package = $this->model->find_package_for_update($package_id); return $this->question_write('create', 0, $package, $data); }
    public function update_question($id, $data) { $question = $this->model->find_question_for_update($id); $package = $question ? $this->model->find_package_for_update($question->package_id) : NULL; return $this->question_write('update', $id, $package, $data); }
    public function delete_question($id) { $question = $this->model->find_question_for_update($id); return $this->delete_write('spmi_instrument_questions', $id, $question ? $question->package_id : 0, TRUE); }
    public function create_rubric($question_id, $data) { $question = $this->model->find_question_for_update($question_id); return $this->rubric_write('create', 0, $question, $data); }
    public function update_rubric($id, $data) { $rubric = $this->model->find_rubric($id); $question = $rubric ? $this->model->find_question_for_update($rubric->question_id) : NULL; return $this->rubric_write('update', $id, $question, $data); }
    public function delete_rubric($id) { $question = $this->model->find_question_for_rubric($id); return $this->delete_write('spmi_instrument_rubrics', $id, $question ? $question->package_id : 0, TRUE); }
    private function package_write($mode, $id, $standard, $data) { $this->ci->db->trans_begin(); try { $version = $standard ? $this->model->find_version($standard->version_id, TRUE) : NULL; if (!$standard || !$this->is_mutable($version)) return $this->rollback('Paket berada pada versi hanya-baca.'); $code = strtoupper(trim((string) (isset($data['package_code']) ? $data['package_code'] : ''))); $order = (int) (isset($data['display_order']) ? $data['display_order'] : 0); $title = trim((string) (isset($data['title']) ? $data['title'] : '')); if (!preg_match('/^[A-Z0-9._-]+$/', $code) || strlen($code) > 64 || $order < 1 || $title === '' || strlen($title) > 200) return $this->rollback('Kode, urutan, dan judul paket tidak valid.'); if ($this->model->find_package_by_code($standard->id, $code, $id) || $this->model->find_package_by_order($standard->id, $order, $id)) return $this->rollback('Kode atau urutan paket sudah digunakan.'); $payload = ['standard_id' => (int) $standard->id, 'package_code' => $code, 'display_order' => $order, 'title' => $title, 'description' => trim((string) (isset($data['description']) ? $data['description'] : '')) ?: NULL]; $ok = $mode === 'create' ? $this->model->create('spmi_instrument_packages', $payload) : $this->model->update('spmi_instrument_packages', $id, $payload); return $this->finish($ok, $ok ? 'Paket instrumen berhasil disimpan.' : 'Paket instrumen gagal disimpan.'); } catch (Throwable $e) { return $this->rollback('Paket instrumen gagal disimpan.'); } }
    private function question_write($mode, $id, $package, $data) { $this->ci->db->trans_begin(); try { $standard = $package ? $this->model->find_standard($package->standard_id) : NULL; $version = $standard ? $this->model->find_version($standard->version_id, TRUE) : NULL; $indicator_id = (int) (isset($data['indicator_id']) ? $data['indicator_id'] : 0); $indicator = $this->model->find_indicator($indicator_id); $code = strtoupper(trim((string) (isset($data['question_code']) ? $data['question_code'] : ''))); $order = (int) (isset($data['display_order']) ? $data['display_order'] : 0); $text = trim((string) (isset($data['question_text']) ? $data['question_text'] : '')); $evidence = trim((string) (isset($data['evidence_instruction']) ? $data['evidence_instruction'] : '')); if (!$package || !$standard || !$this->is_mutable($version)) return $this->rollback('Pertanyaan berada pada versi hanya-baca.'); if (!$indicator || (int) $indicator->standard_id !== (int) $standard->id) return $this->rollback('Indikator harus berasal dari standar yang sama.'); if (!preg_match('/^[A-Z0-9._-]+$/', $code) || strlen($code) > 64 || $order < 1 || $text === '' || $evidence === '') return $this->rollback('Kode, urutan, pertanyaan, dan instruksi bukti wajib valid.'); if ($this->model->find_question_by_code($package->id, $code, $id) || $this->model->find_question_by_order($package->id, $order, $id)) return $this->rollback('Kode atau urutan pertanyaan sudah digunakan.'); $payload = ['package_id' => (int) $package->id, 'indicator_id' => $indicator_id, 'question_code' => $code, 'display_order' => $order, 'question_text' => $text, 'evidence_instruction' => $evidence]; $ok = $mode === 'create' ? $this->model->create('spmi_instrument_questions', $payload) : $this->model->update('spmi_instrument_questions', $id, $payload); return $this->finish($ok, $ok ? 'Pertanyaan instrumen berhasil disimpan.' : 'Pertanyaan instrumen gagal disimpan.'); } catch (Throwable $e) { return $this->rollback('Pertanyaan instrumen gagal disimpan.'); } }
    private function rubric_write($mode, $id, $question, $data) { $this->ci->db->trans_begin(); try { $package = $question ? $this->model->find_package_for_update($question->package_id) : NULL; $standard = $package ? $this->model->find_standard($package->standard_id) : NULL; $version = $standard ? $this->model->find_version($standard->version_id, TRUE) : NULL; $score = (int) (isset($data['score']) ? $data['score'] : 0); $descriptor = trim((string) (isset($data['descriptor']) ? $data['descriptor'] : '')); if (!$question || !$this->is_mutable($version) || $score < 1 || $score > 4 || $descriptor === '') return $this->rollback('Rubrik harus berada pada versi draft/review, skor 1-4, dan deskriptor wajib diisi.'); $duplicate = $this->ci->db->where(['question_id' => (int) $question->id, 'score' => $score])->where($id ? 'id != ' . (int) $id : '1=1', NULL, FALSE)->get('spmi_instrument_rubrics')->row(); if ($duplicate) return $this->rollback('Skor rubrik sudah digunakan.'); $payload = ['question_id' => (int) $question->id, 'score' => $score, 'descriptor' => $descriptor]; $ok = $mode === 'create' ? $this->model->create('spmi_instrument_rubrics', $payload) : $this->model->update('spmi_instrument_rubrics', $id, $payload); return $this->finish($ok, $ok ? 'Rubrik berhasil disimpan.' : 'Rubrik gagal disimpan.'); } catch (Throwable $e) { return $this->rollback('Rubrik gagal disimpan.'); } }
    private function delete_write($table, $id, $package_id, $question_parent = FALSE) { $this->ci->db->trans_begin(); try { $package = $this->model->find_package_for_update($package_id); $standard = $package ? $this->model->find_standard($package->standard_id) : NULL; $version = $standard ? $this->model->find_version($standard->version_id, TRUE) : NULL; if (!$id || !$package || !$this->is_mutable($version)) return $this->rollback('Data instrumen berada pada versi hanya-baca atau tidak ditemukan.'); if ($table === 'spmi_instrument_questions' && $this->model->count_rubrics($id) > 0) return $this->rollback('Pertanyaan tidak dapat dihapus karena masih memiliki rubrik.'); return $this->finish($this->model->delete($table, $id), 'Data instrumen berhasil dihapus.'); } catch (Throwable $e) { return $this->rollback('Data instrumen gagal dihapus.'); } }
    private function finish($ok, $message) { if (!$ok || !$this->ci->db->trans_status()) { $this->ci->db->trans_rollback(); return ['success' => FALSE, 'message' => $message]; } $this->ci->db->trans_commit(); return ['success' => TRUE, 'message' => $message]; }
    private function rollback($message) { $this->ci->db->trans_rollback(); return ['success' => FALSE, 'message' => $message]; }
}
