<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Spmi_rtm_follow_ups_service
{
    const TRANSITIONS = ['open' => ['in_progress'], 'in_progress' => ['completed'], 'completed' => []];
    protected $ci;
    protected $model;

    public function __construct() { $this->ci = &get_instance(); $this->ci->load->model('Spmi_rtm_follow_ups_model'); $this->model = $this->ci->Spmi_rtm_follow_ups_model; }
    public function follow_ups() { return $this->model->follow_ups(); }
    public function follow_up($id) { return $this->model->detail($id); }
    public function form_options() { return ['decisions' => $this->model->resolved_decisions(), 'users' => $this->model->users()]; }
    public function create($decision_id, $data, $user_id) { $this->ci->db->trans_begin(); $decision = $this->model->resolved_decision_for_update($decision_id); if (!$decision || $decision->meeting_status !== 'resolved') return $this->rollback('Keputusan RTM belum resolved atau tidak ditemukan.'); if ($this->model->follow_up_by_decision_for_update($decision_id)) return $this->rollback('Keputusan RTM sudah memiliki tindak lanjut.'); $responsible = $this->model->user_for_update((int) ($data['responsible_user_id'] ?? 0)); if (!$responsible) return $this->rollback('Penanggung jawab tidak ditemukan.'); $payload = $this->payload($data); if (!$this->valid_payload($payload)) return $this->rollback('Tanggal dan catatan tindak lanjut tidak valid.'); $id = $this->model->insert_follow_up(['follow_up_code' => 'RTM-FU-' . (int) $decision_id, 'decision_id' => (int) $decision_id, 'decision_text_snapshot' => $decision->decision_text, 'action_text_snapshot' => $decision->action_text, 'responsible_user_id' => (int) $responsible->id, 'responsible_name_snapshot' => $responsible->nama, 'responsible_email_snapshot' => $responsible->email, 'responsible_role_snapshot' => $responsible->role, 'due_date' => $payload['due_date'], 'follow_up_note' => $payload['follow_up_note'], 'created_by' => (int) $user_id]); if (!$id) return $this->rollback('Tindak lanjut RTM gagal disimpan.'); return $this->finish(['success' => TRUE, 'message' => 'Tindak lanjut RTM berhasil dibuat.', 'id' => $id]); }
    public function update($id, $data) { $this->ci->db->trans_begin(); $follow_up = $this->model->follow_up($id, TRUE); if (!$follow_up || $follow_up->status !== 'open') return $this->rollback('Tindak lanjut hanya dapat diubah saat open.'); $responsible = $this->model->user_for_update((int) ($data['responsible_user_id'] ?? 0)); $payload = $this->payload($data); if (!$responsible || !$this->valid_payload($payload)) return $this->rollback('Tanggal, penanggung jawab, dan catatan wajib valid.'); $ok = $this->model->update_follow_up($id, ['responsible_user_id' => (int) $responsible->id, 'responsible_name_snapshot' => $responsible->nama, 'responsible_email_snapshot' => $responsible->email, 'responsible_role_snapshot' => $responsible->role, 'due_date' => $payload['due_date'], 'follow_up_note' => $payload['follow_up_note']]); return $this->finish($ok ? ['success' => TRUE, 'message' => 'Tindak lanjut RTM berhasil diperbarui.', 'id' => (int) $id] : ['success' => FALSE, 'message' => 'Tindak lanjut RTM gagal diperbarui.']); }
    public function transition($id, $status, $data, $user_id) { $this->ci->db->trans_begin(); $follow_up = $this->model->follow_up($id, TRUE); if (!$follow_up || !isset(self::TRANSITIONS[$follow_up->status]) || !in_array($status, self::TRANSITIONS[$follow_up->status], TRUE)) return $this->rollback('Transisi status tindak lanjut tidak diizinkan.'); $completion_note = trim((string) ($data['completion_note'] ?? '')); if ($status === 'completed' && $completion_note === '') return $this->rollback('Catatan penyelesaian wajib diisi.'); $fields = ['status' => $status]; if ($status === 'in_progress') $fields += ['started_by' => (int) $user_id, 'started_at' => date('Y-m-d H:i:s')]; if ($status === 'completed') $fields += ['completion_note' => $completion_note, 'completed_by' => (int) $user_id, 'completed_at' => date('Y-m-d H:i:s')]; return $this->finish($this->model->update_follow_up($id, $fields) ? ['success' => TRUE, 'message' => 'Status tindak lanjut berhasil diubah.', 'id' => (int) $id] : ['success' => FALSE, 'message' => 'Status tindak lanjut gagal diubah.']); }
    protected function payload($data) { return ['due_date' => trim((string) ($data['due_date'] ?? '')) ?: NULL, 'follow_up_note' => trim((string) ($data['follow_up_note'] ?? '')) ?: NULL]; }
    protected function valid_payload($payload) { return strlen((string) $payload['follow_up_note']) <= 10000 && ($payload['due_date'] === NULL || (DateTime::createFromFormat('!Y-m-d', $payload['due_date']) && DateTime::createFromFormat('!Y-m-d', $payload['due_date'])->format('Y-m-d') === $payload['due_date'])); }
    protected function rollback($message) { $this->ci->db->trans_rollback(); return ['success' => FALSE, 'message' => $message]; }
    protected function finish($result) { $this->ci->db->trans_complete(); return $this->ci->db->trans_status() ? $result : ['success' => FALSE, 'message' => 'Tindak lanjut RTM gagal disimpan.']; }
}
