<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$assignments = isset($assignments) && is_array($assignments) ? $assignments : [];
$type_labels = ['university' => 'Universitas', 'faculty' => 'Fakultas', 'study_program' => 'Program Studi', 'bureau' => 'Biro', 'unit' => 'Unit', 'institute' => 'Lembaga', 'upps' => 'UPPS'];
$unit_type = (string) $unit->type;
$today = date('Y-m-d');
$is_current = static function ($assignment, $today) { return (string) $assignment->valid_from <= $today && (empty($assignment->valid_until) || (string) $assignment->valid_until > $today); };

include APPPATH . 'views/layouts/header.php';
include APPPATH . 'views/layouts/sidebar.php';
?>

<main class="master-data-root">
    <div class="master-data-breadcrumb">Beranda / Management / Master Data Organisasi &amp; Staf / Detail Unit</div>
    <section class="ami-panel mb-3"><div class="ami-panel-body"><div class="master-directory-head"><div><div class="ami-eyebrow">Unit organisasi</div><h2 class="ami-section-title mb-1"><?php echo html_escape($unit->name); ?></h2><p class="master-code mb-0"><?php echo html_escape($unit->code); ?> · <?php echo html_escape(isset($type_labels[$unit_type]) ? $type_labels[$unit_type] : $unit_type); ?></p></div><div class="master-controls"><a class="btn btn-outline-ami btn-ami" href="<?php echo html_escape(site_url('lpmpi/master-data-prodi-staf')); ?>">Kembali</a><?php if ($unit->parent_id !== NULL && $unit_type !== 'study_program'): ?><a class="btn btn-primary btn-ami" href="<?php echo html_escape(site_url('lpmpi/master-data-prodi-staf/unit/edit/' . (int) $unit->id)); ?>">Edit Unit</a><?php endif; ?></div></div><div class="form-row mb-0"><div class="col-md-4"><small class="text-muted d-block">Parent</small><strong><?php echo html_escape($unit->parent_id === NULL ? 'Root' : ($parent_unit ? $parent_unit->name . ' (' . $parent_unit->code . ')' : 'Unit induk tidak ditemukan')); ?></strong></div><div class="col-md-4"><small class="text-muted d-block">Status</small><span class="master-status-badge <?php echo (int) $unit->is_active === 1 ? 'master-status-active' : 'master-status-inactive'; ?>"><?php echo (int) $unit->is_active === 1 ? 'Aktif' : 'Nonaktif'; ?></span></div><div class="col-md-4"><small class="text-muted d-block">Tipe</small><strong><?php echo html_escape(isset($type_labels[$unit_type]) ? $type_labels[$unit_type] : $unit_type); ?></strong></div></div></div></section>
    <section class="ami-panel" aria-labelledby="unit-placement-title"><div class="ami-panel-body"><div class="master-directory-head"><div><h3 id="unit-placement-title">Penempatan Non-Prodi</h3><p>Riwayat penempatan pada unit ini. Penempatan aktif yang sedang berlaku dapat diakhiri.</p></div></div><?php if (empty($assignments)): ?><div class="ami-empty">Belum ada penempatan pada unit ini.</div><?php else: ?><div class="master-table-wrap"><table class="table ami-table"><thead><tr><th>Pengguna</th><th>Posisi</th><th>Masa Berlaku</th><th>Status</th><th class="text-right">Aksi</th></tr></thead><tbody><?php foreach ($assignments as $assignment): ?><?php $current = $is_current($assignment, $today); ?><tr><td><strong><?php echo html_escape($assignment->nama); ?></strong><span class="master-subtext"><?php echo html_escape($assignment->email); ?></span></td><td><?php echo html_escape($assignment->position_code); ?><?php if ((int) $assignment->is_primary === 1): ?> <span class="master-mapping-badge master-mapping-mapped">Utama</span><?php endif; ?></td><td><?php echo html_escape($assignment->valid_from); ?> s/d <?php echo html_escape($assignment->valid_until ?: 'Sekarang'); ?></td><td><span class="master-status-badge <?php echo $current ? 'master-status-active' : 'master-status-inactive'; ?>"><?php echo $current ? 'Aktif' : 'Selesai / Terjadwal'; ?></span></td><td class="text-right"><?php if ($current && in_array($unit_type, ['faculty', 'bureau', 'unit', 'institute'], TRUE)): ?><?php echo form_open('lpmpi/master-data-prodi-staf/placement/end/' . (int) $assignment->id, ['class' => 'd-inline']); ?><input type="hidden" name="valid_until" value="<?php echo html_escape($today); ?>"><button type="submit" class="btn btn-sm btn-outline-danger" onclick="return window.confirm('Akhiri penempatan ini?');">Akhiri</button><?php echo form_close(); ?><?php else: ?><span class="text-muted small">-</span><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></section>
</main>

<?php include APPPATH . 'views/layouts/footer.php'; ?>
